import React, { useEffect, useMemo, useState } from 'react';
import { buildRigFromMap, CharacterRig } from './rigEngine';
import { bindCharacterToRig, loadBoundRig } from '../character/characterBinding';
import { loadActiveCharacterAssetId } from '../character/characterReplacement';

export type RigPoint={id:string;label:string;x:number;y:number;group:'body'|'face'|'mouth'|'hair'};
export const initialPoints:RigPoint[]=[
{id:'head',label:'Head',x:50,y:16,group:'body'},{id:'neck',label:'Neck',x:50,y:25,group:'body'},{id:'spine',label:'Spine',x:50,y:43,group:'body'},{id:'pelvis',label:'Pelvis',x:50,y:60,group:'body'},
{id:'l-shoulder',label:'L Shoulder',x:36,y:30,group:'body'},{id:'r-shoulder',label:'R Shoulder',x:64,y:30,group:'body'},{id:'l-elbow',label:'L Elbow',x:27,y:45,group:'body'},{id:'r-elbow',label:'R Elbow',x:73,y:45,group:'body'},{id:'l-hand',label:'L Hand',x:21,y:60,group:'body'},{id:'r-hand',label:'R Hand',x:79,y:60,group:'body'},
{id:'l-knee',label:'L Knee',x:43,y:76,group:'body'},{id:'r-knee',label:'R Knee',x:57,y:76,group:'body'},{id:'l-ankle',label:'L Ankle',x:40,y:90,group:'body'},{id:'r-ankle',label:'R Ankle',x:60,y:90,group:'body'},{id:'l-toe',label:'L Toe',x:38,y:96,group:'body'},{id:'r-toe',label:'R Toe',x:62,y:96,group:'body'},
{id:'l-eye',label:'L Eye',x:46,y:17,group:'face'},{id:'r-eye',label:'R Eye',x:54,y:17,group:'face'},{id:'brow-l',label:'L Brow',x:46,y:13,group:'face'},{id:'brow-r',label:'R Brow',x:54,y:13,group:'face'},{id:'mouth',label:'Mouth',x:50,y:23,group:'mouth'},{id:'hair',label:'Hair',x:50,y:8,group:'hair'}];
const bones:[string,string][]=[['head','neck'],['neck','spine'],['spine','pelvis'],['neck','l-shoulder'],['l-shoulder','l-elbow'],['l-elbow','l-hand'],['neck','r-shoulder'],['r-shoulder','r-elbow'],['r-elbow','r-hand'],['pelvis','l-knee'],['l-knee','l-ankle'],['l-ankle','l-toe'],['pelvis','r-knee'],['r-knee','r-ankle'],['r-ankle','r-toe']];
type Props={image?:string|null;onRigCreated?:(rig:CharacterRig)=>void};
export default function RigMapCanvas({image,onRigCreated}:Props){
 const [points,setPoints]=useState(initialPoints),[selected,setSelected]=useState('head'),[activeGroup,setActiveGroup]=useState<RigPoint['group']|'all'>('all'),[status,setStatus]=useState('Ready for mapping');
 useEffect(()=>{const restored=loadBoundRig();if(restored){onRigCreated?.(restored);setStatus(`Saved rig restored • ${restored.bones.length} bones`)}},[onRigCreated]);
 const visible=useMemo(()=>activeGroup==='all'?points:points.filter(p=>p.group===activeGroup),[points,activeGroup]);
 const movePoint=(id:string,e:React.PointerEvent<HTMLButtonElement>)=>{const stage=e.currentTarget.parentElement;if(!stage)return;const r=stage.getBoundingClientRect();const x=Math.max(2,Math.min(98,(e.clientX-r.left)/r.width*100));const y=Math.max(2,Math.min(98,(e.clientY-r.top)/r.height*100));setPoints(p=>p.map(q=>q.id===id?{...q,x,y}:q));setStatus('Map edited • unsaved')};
 const pointById=(id:string)=>points.find(p=>p.id===id)!;
 const createRig=()=>{const rig=buildRigFromMap(points);const assetId=loadActiveCharacterAssetId();if(assetId)bindCharacterToRig(assetId,rig);onRigCreated?.(rig);setStatus(assetId?`Rig generated • ${rig.bones.length} bones • character binding saved`:`Rig generated • ${rig.bones.length} bones • import a character to persist binding`)};
 return <section className="rig-map-panel"><header className="rig-map-header"><div><span className="eyebrow">CHARACTER / RIG MAP</span><h2>Automatic Rig Mapping</h2><p>Place controls on the imported character. Body, face and expression controls remain editable.</p></div><div className="rig-map-actions"><span className="image-state">{image?'● Character loaded':'○ Guide mode'}</span><button onClick={()=>{setPoints(initialPoints);setStatus('Map reset')}}>Reset Map</button><button className="primary" onClick={createRig}>Create Rig</button></div></header>
 <div className="rig-filter-row">{(['all','body','face','mouth','hair'] as const).map(g=><button key={g} className={activeGroup===g?'active':''} onClick={()=>setActiveGroup(g)}>{g==='all'?'All Points':g[0].toUpperCase()+g.slice(1)}</button>)}<span className="map-status">{points.length} controls • 16 bone joints • 2 eye anchors</span></div>
 <div className="rig-map-stage">{image?<img src={image} className="rig-character-image" alt="Imported character for rig mapping"/>:<div className="character-guide"><div className="guide-head"/><div className="guide-neck"/><div className="guide-torso"/><div className="guide-arm left"/><div className="guide-arm right"/><div className="guide-leg left"/><div className="guide-leg right"/><div className="guide-eye left"/><div className="guide-eye right"/><div className="guide-mouth"/></div>}<svg className="rig-bones" viewBox="0 0 100 100" preserveAspectRatio="none">{bones.map(([a,b])=>{const p1=pointById(a),p2=pointById(b);return <line key={a+b} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y}/>})}</svg>{visible.map(p=><button key={p.id} className={`rig-point ${p.group} ${selected===p.id?'selected':''}`} style={{left:`${p.x}%`,top:`${p.y}%`}} onPointerDown={e=>{setSelected(p.id);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))movePoint(p.id,e)}} title={p.label}><span/><b>{p.label}</b></button>)}<div className="stage-hint">DRAG CONTROLS • ALIGN TO CHARACTER • CREATE RIG</div></div>
 <footer className="rig-map-footer"><div><strong>Selected:</strong> {pointById(selected)?.label}</div><div><strong>Status:</strong> {status}</div><div><strong>Pipeline:</strong> Detect → Correct → Skeleton → IK → Deformers → Expressions</div></footer></section>;
}