import React,{useMemo,useRef,useState} from 'react';
import {builtInPresets,loadCustomPresets,presetCategories,saveCustomPresets,StudioPreset,PresetCategory} from './presetModel';
import MotionStudioPanel from '../animation/MotionStudioPanel';
import './presetLibrary.css';

type Props={onUse?:(preset:StudioPreset)=>void;onStatus?:(message:string)=>void};

export default function PresetLibrary({onUse,onStatus}:Props){
 const [category,setCategory]=useState<PresetCategory|'all'>('all');
 const [query,setQuery]=useState('');
 const [custom,setCustom]=useState<StudioPreset[]>(loadCustomPresets);
 const [mode,setMode]=useState<'library'|'motion'>('library');
 const fileRef=useRef<HTMLInputElement>(null);
 const presets=useMemo(()=>[...builtInPresets,...custom].filter(p=>(category==='all'||p.category===category)&&(!query||`${p.name} ${p.description} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))),[category,custom,query]);
 const importPreset=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));const list:Array<StudioPreset>=Array.isArray(parsed)?parsed:[parsed];const valid=list.filter(p=>p&&p.name&&p.category);const next=[...custom,...valid.map(p=>({...p,id:`custom-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,builtIn:false,createdAt:p.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}))];setCustom(next);saveCustomPresets(next);onStatus?.(`${valid.length} preset${valid.length===1?'':'s'} added to library`)}catch{onStatus?.('Invalid preset package')}};reader.readAsText(f);e.target.value=''};
 const exportLibrary=()=>{const blob=new Blob([JSON.stringify(custom,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='maya-shadow-preset-library.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const saveAssetAsPreset=(category:PresetCategory)=>{const input=document.createElement('input');input.type='file';input.accept=category==='character'||category==='background'?'image/*':'application/json';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const p:StudioPreset={id:`custom-${Date.now()}`,name:f.name.replace(/\.[^.]+$/,''),category,description:`User library preset • ${f.name}`,tags:['custom',category],source:String(reader.result),sourceType:category==='character'||category==='background'?'image':'json',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),builtIn:false};const next=[...custom,p];setCustom(next);saveCustomPresets(next);onStatus?.(`${p.name} saved as ${category} preset`)};reader.readAsDataURL(f)};input.click()};
 if(mode==='motion')return <MotionStudioPanel onStatus={onStatus}/>;
 return <div className="preset-library"><div className="preset-header"><div><div className="preset-kicker">MAYA SHADOW LIBRARY</div><h2>Presets</h2><p>Characters, backgrounds, animation and production presets — built to grow with your studio.</p></div><div className="preset-actions"><button onClick={()=>setMode('motion')}>🎞 Motion + Scene Builder</button><button onClick={()=>fileRef.current?.click()}>⇩ Import Package</button><button onClick={exportLibrary} disabled={!custom.length}>⇧ Export My Library</button></div></div><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={importPreset}/><div className="preset-tabs"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All</button>{presetCategories.map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.icon} {c.label}</button>)}</div><div className="preset-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search presets…"/><span>{presets.length} presets</span></div><div className="preset-grid">{presets.map(p=><article className="preset-card" key={p.id}><div className={`preset-thumb ${p.source?'has-source':''}`}>{p.sourceType==='image'&&p.source?<img src={p.source} alt=""/>:<><b>{presetCategories.find(c=>c.id===p.category)?.icon}</b><small>{p.category.toUpperCase()}</small></>}</div><div className="preset-copy"><h3>{p.name}</h3><p>{p.description}</p><div className="preset-tags">{p.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div></div><div className="preset-card-actions"><button className="use" onClick={()=>{onUse?.(p);onStatus?.(`${p.name} selected`);}}>Use Preset</button>{!p.builtIn&&<button onClick={()=>{const next=custom.filter(x=>x.id!==p.id);setCustom(next);saveCustomPresets(next)}}>Delete</button>}</div></article>)}</div><div className="preset-add-row"><div><b>Grow your library</b><span>Keep your own character and background packs locally. Add animation/FX/voice JSON packages later without changing the app.</span></div><div><button onClick={()=>saveAssetAsPreset('character')}>＋ Character</button><button onClick={()=>saveAssetAsPreset('background')}>＋ Background</button><button onClick={()=>saveAssetAsPreset('animation')}>＋ Animation</button><button onClick={()=>saveAssetAsPreset('fx')}>＋ FX</button></div></div></div>
}
