import React,{useMemo,useRef,useState} from 'react';
import {builtInPresets,loadCustomPresets,presetCategories,saveCustomPresets,StudioPreset,PresetCategory} from './presetModel';
import MotionStudioPanel from '../animation/MotionStudioPanel';
import './presetLibrary.css';

type Props={onUse?:(preset:StudioPreset)=>void;onStatus?:(message:string)=>void;onApplyMotion?:(frames:Array<{frame:number;pose:Record<string,{rotation:number}>}>,meta:{source:string;fps:number;target:string;scale:number;mirror:boolean;rootMotion:boolean})=>void};
type Mode='library'|'motion'|'replace'|'help';

const helpCards=[
 {title:'Character → Rig → Animate',text:'Character preset বা image নিন, Character workspace-এ Auto Rig Map করুন, তারপর Rig Editor-এ pose keyframe দিন। Motion + Scene Builder থেকে BVH motion এনে Rig Controls timeline-এ apply করা যায়.'},
 {title:'Character Replacement',text:'Replace Character workflow-এ নতুন character preview করুন। Replace করলে active character image বদলানোর জন্য preset workflow ব্যবহার করুন; আগের project timeline ও scene data আলাদা থাকে.'},
 {title:'Scene Builder',text:'Motion + Scene Builder-এ character, background, props এবং vehicle বেছে scene template তৈরি করুন। Scene পরিবর্তন করার আগে Save Project করুন যাতে recovery snapshot-ও আপডেট থাকে.'},
 {title:'Timeline Basics',text:'◆ keyframe দিয়ে frame ধরে pose/face/transform save করুন। একই frame/property-তে নতুন keyframe দিলে আগেরটি replace হয়. Preview চাপলে scene fps অনুযায়ী timeline চলে.'},
 {title:'Import / Export',text:'Preset Package JSON import/export করুন। Project Save Project দিয়ে .maya.json snapshot রাখুন। Rig Template আলাদাভাবে .mayarig.json হিসেবে রাখা যায়.'},
 {title:'Beginner Tip',text:'প্রথমে Character → Background → Rig → Motion → Voice → Preview → Export এই ক্রমে কাজ করুন। পরে Professional workflow-এ একই tools আরও দ্রুত ব্যবহার করতে পারবেন.'}
];

export default function PresetLibrary({onUse,onStatus,onApplyMotion}:Props){
 const [category,setCategory]=useState<PresetCategory|'all'>('all');
 const [query,setQuery]=useState('');
 const [custom,setCustom]=useState<StudioPreset[]>(loadCustomPresets);
 const [mode,setMode]=useState<Mode>('library');
 const [replaceQuery,setReplaceQuery]=useState('');
 const fileRef=useRef<HTMLInputElement>(null);
 const presets=useMemo(()=>[...builtInPresets,...custom].filter(p=>(category==='all'||p.category===category)&&(!query||`${p.name} ${p.description} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))),[category,custom,query]);
 const characterPresets=useMemo(()=>[...builtInPresets,...custom].filter(p=>p.category==='character'&&(!replaceQuery||`${p.name} ${p.description} ${p.tags.join(' ')}`.toLowerCase().includes(replaceQuery.toLowerCase()))),[custom,replaceQuery]);
 const importPreset=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));const list:Array<StudioPreset>=Array.isArray(parsed)?parsed:[parsed];const valid=list.filter(p=>p&&p.name&&p.category);const next=[...custom,...valid.map(p=>({...p,id:`custom-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,builtIn:false,createdAt:p.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}))];setCustom(next);saveCustomPresets(next);onStatus?.(`${valid.length} preset${valid.length===1?'':'s'} added to library`)}catch{onStatus?.('Invalid preset package')}};reader.readAsText(f);e.target.value=''};
 const exportLibrary=()=>{const blob=new Blob([JSON.stringify(custom,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='maya-shadow-preset-library.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const saveAssetAsPreset=(category:PresetCategory)=>{const input=document.createElement('input');input.type='file';input.accept=category==='character'||category==='background'?'image/*':'application/json';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const p:StudioPreset={id:`custom-${Date.now()}`,name:f.name.replace(/\.[^.]+$/,''),category,description:`User library preset • ${f.name}`,tags:['custom',category],source:String(reader.result),sourceType:category==='character'||category==='background'?'image':'json',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),builtIn:false};const next=[...custom,p];setCustom(next);saveCustomPresets(next);onStatus?.(`${p.name} saved as ${category} preset`)};reader.readAsDataURL(f)};input.click()};
 if(mode==='motion')return <div><button className="wide" onClick={()=>setMode('library')}>← Back to Library</button><MotionStudioPanel onStatus={onStatus} onApplyMotion={onApplyMotion}/></div>;
 if(mode==='replace')return <div className="preset-library"><div className="preset-header"><div><div className="preset-kicker">CHARACTER WORKFLOW</div><h2>Character Replacement</h2><p>Choose a replacement character without rebuilding the whole scene workflow.</p></div><div className="preset-actions"><button onClick={()=>setMode('library')}>← Library</button><button onClick={()=>setMode('help')}>❔ Help</button></div></div><div className="preset-tools"><input value={replaceQuery} onChange={e=>setReplaceQuery(e.target.value)} placeholder="Search character presets…"/><span>{characterPresets.length} characters</span></div><div className="preset-grid">{characterPresets.map(p=><article className="preset-card" key={p.id}><div className={`preset-thumb ${p.source?'has-source':''}`}>{p.sourceType==='image'&&p.source?<img src={p.source} alt=""/>:<><b>👤</b><small>CHARACTER</small></>}</div><div className="preset-copy"><h3>{p.name}</h3><p>{p.description}</p><div className="preset-tags">{p.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div></div><div className="preset-card-actions"><button className="use" onClick={()=>{onUse?.(p);onStatus?.(`Character replaced with ${p.name} • continue in Character workspace`);setMode('library')}}>Replace Character</button></div></article>)}</div><div className="preset-add-row"><div><b>Need a new character?</b><span>Add an image as a local character preset, then use it here whenever you need a replacement.</span></div><button onClick={()=>saveAssetAsPreset('character')}>＋ Add Character</button></div></div>;
 if(mode==='help')return <div className="preset-library"><div className="preset-header"><div><div className="preset-kicker">MAYA SHADOW GUIDE</div><h2>Beginner Help & Tutorials</h2><p>Quick guidance for the main Studio workflow. These cards are intentionally simple and action-focused.</p></div><div className="preset-actions"><button onClick={()=>setMode('library')}>← Back</button></div></div><div className="preset-grid">{helpCards.map(card=><article className="preset-card" key={card.title}><div className="preset-copy"><h3>{card.title}</h3><p>{card.text}</p></div></article>)}</div><div className="preset-add-row"><div><b>Recommended first project</b><span>Import one character, add one background, create a rig, apply a few motion poses, add voice/audio, preview, then export.</span></div><button onClick={()=>{setMode('replace');onStatus?.('Start with Character Replacement')}}>Start Character Workflow</button></div></div>;
 return <div className="preset-library"><div className="preset-header"><div><div className="preset-kicker">MAYA SHADOW LIBRARY</div><h2>Presets</h2><p>Characters, backgrounds, animation and production presets — built to grow with your studio.</p></div><div className="preset-actions"><button onClick={()=>setMode('replace')}>👤 Character Replace</button><button onClick={()=>setMode('motion')}>🎞 Motion + Scene Builder</button><button onClick={()=>setMode('help')}>❔ Beginner Help</button><button onClick={()=>fileRef.current?.click()}>⇩ Import Package</button><button onClick={exportLibrary} disabled={!custom.length}>⇧ Export My Library</button></div></div><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={importPreset}/><div className="preset-tabs"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All</button>{presetCategories.map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.icon} {c.label}</button>)}</div><div className="preset-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search presets…"/><span>{presets.length} presets</span></div><div className="preset-grid">{presets.map(p=><article className="preset-card" key={p.id}><div className={`preset-thumb ${p.source?'has-source':''}`}>{p.sourceType==='image'&&p.source?<img src={p.source} alt=""/>:<><b>{presetCategories.find(c=>c.id===p.category)?.icon}</b><small>{p.category.toUpperCase()}</small></>}</div><div className="preset-copy"><h3>{p.name}</h3><p>{p.description}</p><div className="preset-tags">{p.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div></div><div className="preset-card-actions"><button className="use" onClick={()=>{onUse?.(p);onStatus?.(`${p.name} selected`);}}>Use Preset</button>{!p.builtIn&&<button onClick={()=>{const next=custom.filter(x=>x.id!==p.id);setCustom(next);saveCustomPresets(next)}}>Delete</button>}</div></article>)}</div><div className="preset-add-row"><div><b>Grow your library</b><span>Keep your own character and background packs locally. Add animation/FX/voice JSON packages later without changing the app.</span></div><div><button onClick={()=>saveAssetAsPreset('character')}>＋ Character</button><button onClick={()=>saveAssetAsPreset('background')}>＋ Background</button><button onClick={()=>saveAssetAsPreset('animation')}>＋ Animation</button><button onClick={()=>saveAssetAsPreset('fx')}>＋ FX</button></div></div></div>
}
