import React,{useMemo,useState} from 'react';

type Clip={id:string;name:string;kind:'audio'|'video';url:string;duration:number};
const effects=['Voice Cleanup','Noise Reduction','DeHum 50/60Hz','DeEsser','Parametric EQ','Compressor','Limiter','Loudness Normalize'];
export default function MediaEditorPlugin({onStatus}:{onStatus?:(s:string)=>void}){
 const [clips,setClips]=useState<Clip[]>([]);const [selected,setSelected]=useState<string>('');const [gain,setGain]=useState(0);const [eq,setEq]=useState(0);const [selectedFx,setSelectedFx]=useState<string[]>(['Voice Cleanup']);const [inPoint,setInPoint]=useState(0);const [outPoint,setOutPoint]=useState(10);
 const active=clips.find(c=>c.id===selected);const total=active?.duration||0;
 const add=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const kind=f.type.startsWith('video/')?'video':'audio';const url=URL.createObjectURL(f);const el=document.createElement(kind);el.preload='metadata';el.onloadedmetadata=()=>{const c={id:`clip-${Date.now()}`,name:f.name,kind,url,duration:Number.isFinite(el.duration)?el.duration:0};setClips(x=>[...x,c]);setSelected(c.id);setOutPoint(c.duration);onStatus?.(`${kind==='audio'?'Audio':'Video'} loaded into Media Studio`)};el.src=url;e.target.value=''};
 const toggleFx=(fx:string)=>setSelectedFx(x=>x.includes(fx)?x.filter(v=>v!==fx):[...x,fx]);
 const exportPlan=()=>{const plan={version:1,type:'maya-shadow-media-edit',clip:active?{name:active.name,kind:active.kind,duration:active.duration}:null,trim:{in:inPoint,out:Math.min(outPoint,total)},audio:{gainDb:gain,equalizerDb:eq,effects:selectedFx},createdAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(plan,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='maya-shadow-media-edit.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);onStatus?.('Media edit plan exported')};
 const preview=useMemo(()=>active?active.kind==='audio'?<audio controls src={active.url}/>:<video controls src={active.url} style={{maxWidth:'100%',maxHeight:240}}/>:null,[active]);
 return <div className="plugin-tool"><div className="plugin-tool-head"><div><b>MEDIA EDITOR PRO</b><small>Audition/Audacity-style audio workflow + animation video editing</small></div><span>FFMPEG READY</span></div><div className="plugin-media-grid"><section><h4>Media</h4><input type="file" accept="audio/*,video/*" onChange={add}/><div className="plugin-media-list">{clips.map(c=><button className={c.id===selected?'selected':''} key={c.id} onClick={()=>{setSelected(c.id);setOutPoint(c.duration)}}><b>{c.kind.toUpperCase()}</b> {c.name}</button>)}</div>{preview}</section><section><h4>Audio Mastering</h4><div className="plugin-fx-grid">{effects.map(f=><button className={selectedFx.includes(f)?'selected':''} key={f} onClick={()=>toggleFx(f)}>{f}</button>)}</div><label>Gain: {gain.toFixed(1)} dB<input type="range" min="-24" max="24" step="0.5" value={gain} onChange={e=>setGain(Number(e.target.value))}/></label><label>EQ tilt: {eq.toFixed(1)} dB<input type="range" min="-12" max="12" step="0.5" value={eq} onChange={e=>setEq(Number(e.target.value))}/></label></section><section><h4>Video Edit</h4><label>In point (sec)<input type="number" min="0" max={total} step="0.01" value={inPoint} onChange={e=>setInPoint(Math.max(0,Math.min(total,Number(e.target.value)||0)))}/></label><label>Out point (sec)<input type="number" min="0" max={total} step="0.01" value={outPoint} onChange={e=>setOutPoint(Math.max(inPoint,Math.min(total,Number(e.target.value)||0)))}/></label><div className="plugin-cut-info">Trim {Math.max(0,outPoint-inPoint).toFixed(2)}s • Ripple-safe edit plan</div><button className="use" onClick={exportPlan}>⇧ Export Edit Plan</button></section></div><small className="plugin-tool-status">The editor stores a deterministic edit/effect plan. Final waveform/video processing is delegated to the Studio FFmpeg renderer so the UI remains responsive.</small></div>;
}
