import React,{useMemo,useRef,useState} from 'react';
import {mergePlugins,pluginCategories,savePlugins,StudioPlugin,validatePluginManifest} from './pluginModel';
import AutoLipSyncPlugin from './AutoLipSyncPlugin';
import MediaEditorPlugin from './MediaEditorPlugin';
import './pluginManager.css';

type Props={onStatus?:(message:string)=>void};
export default function PluginManager({onStatus}:Props){
 const [plugins,setPlugins]=useState<StudioPlugin[]>(mergePlugins);const [category,setCategory]=useState('all');const [query,setQuery]=useState('');const [tool,setTool]=useState<string|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 const visible=useMemo(()=>plugins.filter(p=>(category==='all'||p.category===category)&&(!query||`${p.name} ${p.description} ${p.author}`.toLowerCase().includes(query.toLowerCase()))),[plugins,category,query]);
 const toggle=(p:StudioPlugin)=>{const enabled=!p.enabled;const next=plugins.map(x=>x.id===p.id?{...x,enabled,installedAt:x.installedAt||new Date().toISOString()}:x);setPlugins(next);savePlugins(next.filter(x=>x.enabled||x.source==='local-package'));onStatus?.(`${p.name} ${enabled?'enabled':'disabled'}`);if(!enabled&&tool===p.id)setTool(null)};
 const update=(p:StudioPlugin)=>{const next=plugins.map(x=>x.id===p.id?{...x,installedAt:new Date().toISOString()}:x);setPlugins(next);savePlugins(next.filter(x=>x.enabled||x.source==='local-package'));onStatus?.(`${p.name}: update check complete • current v${p.version}`)};
 const importPlugin=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=validatePluginManifest(JSON.parse(String(r.result)));if(!p){onStatus?.('Plugin rejected: invalid or unsupported manifest');return}const next=[...plugins.filter(x=>x.id!==p.id),p];setPlugins(next);savePlugins(next);onStatus?.(`${p.name} installed • review permissions before enabling`)}catch{onStatus?.('Plugin rejected: invalid JSON manifest')}};r.readAsText(f);e.target.value=''};
 const remove=(p:StudioPlugin)=>{if(p.source==='builtin'){const next=plugins.map(x=>x.id===p.id?{...x,enabled:false}:x);setPlugins(next);savePlugins(next.filter(x=>x.enabled||x.source==='local-package'));onStatus?.(`${p.name} disabled`);return}const next=plugins.filter(x=>x.id!==p.id);setPlugins(next);savePlugins(next);onStatus?.(`${p.name} removed`)};
 return <div className="plugin-manager"><div className="plugin-header"><div><div className="plugin-kicker">MAYA SHADOW EXTENSIONS</div><h2>Plugin Manager</h2><p>Extend the studio with modular production tools. Built-in plugins remain offline-first and imported manifests are never executed as code.</p></div><div className="plugin-actions"><button onClick={()=>fileRef.current?.click()}>＋ Install Plugin Package</button><input ref={fileRef} hidden type="file" accept="application/json,.json,.mayaplugin.json" onChange={importPlugin}/></div></div><div className="plugin-safety"><b>🔒 Safety first</b><span>Local plugin packages are treated as manifests until an official implementation is available. Review permissions before enabling.</span></div><div className="plugin-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search plugins…"/><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All</button>{pluginCategories.map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.label}</button>)}</div>{tool==='maya-plugin-lipsync'&&<AutoLipSyncPlugin onApply={cues=>onStatus?.(`Auto Lip Sync generated ${cues.length} mouth cues • ready for timeline mapping`)}/>} {tool==='maya-plugin-media-io'&&<MediaEditorPlugin onStatus={onStatus}/>}<div className="plugin-grid">{visible.map(p=><article className={`plugin-card ${p.enabled?'enabled':''}`} key={p.id}><div className="plugin-card-top"><span className="plugin-status">{p.enabled?'ON':'OFF'}</span><span>{p.source==='builtin'?'Built-in':'Local package'}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="plugin-meta"><span>v{p.version}</span><span>{p.author}</span></div><div className="plugin-permissions"><b>Permissions</b><div>{p.permissions.map(x=><span key={x}>{x}</span>)}</div></div><div className="plugin-card-actions"><button className="use" onClick={()=>toggle(p)}>{p.enabled?'Disable':'Enable'}</button><button onClick={()=>update(p)}>Update</button>{(p.id==='maya-plugin-lipsync'||p.id==='maya-plugin-media-io')&&p.enabled&&<button onClick={()=>setTool(tool===p.id?null:p.id)}>{tool===p.id?'Close':'Open'}</button>}<button onClick={()=>remove(p)}>{p.source==='builtin'?'Reset':'Remove'}</button></div></article>)}</div><div className="plugin-roadmap"><b>Production ecosystem</b><span>Smart Rig → Motion Library → Auto Lip Sync → Nature FX → Cinematic Camera → Media I/O → Project Productivity → AI Story Assistant</span></div></div>;
}
