import React,{useMemo,useRef,useState} from 'react';
import {MotionFormat,motionFormatLabels,makeMotionClip,describeRetarget,MotionTarget} from './motionRetarget';
import './motionStudio.css';

type Imported={name:string;format:MotionFormat;size:number;duration:number;fps:number;source?:string};
const formats:MotionFormat[]=['mixamo-fbx','gltf','glb','bvh','vrm','motion-json'];
const scenes={
 characters:['Bengali Young Male','Bengali Young Female','Village Child','Village Elder','Mother','Father','Teacher','Shopkeeper','Ghost Story Character','Shadow Entity','Police','Doctor','Driver'],
 backgrounds:['Bengal Village Courtyard','Riverbank Evening','Rural House Interior','Village Night','Haunted House Exterior','Bengal Forest Path','Village School','Village Market','Roadside Tea Stall','Village Bus Stop','Paddy Field','Village Temple Road'],
 props:['Wooden Chair','Table','Clay Pot','Lantern','Umbrella','Bamboo Basket','Tea Stall Counter','School Bench','Temple Bell','River Boat'],
 vehicles:['Bullock Cart','Motorbike','Car','Village Bus','Bicycle']
};
const detect=(name:string):MotionFormat|null=>{const e=name.toLowerCase().split('.').pop();return e==='fbx'?'mixamo-fbx':e==='gltf'?'gltf':e==='glb'?'glb':e==='bvh'?'bvh':e==='vrm'?'vrm':e==='json'?'motion-json':null};
export default function MotionStudioPanel({onStatus}:{onStatus?:(s:string)=>void}){
 const [tab,setTab]=useState<'motion'|'scene'>('motion');
 const [target,setTarget]=useState<MotionTarget>('2d-bone-rig');
 const [mirror,setMirror]=useState(false);const [rootMotion,setRootMotion]=useState(true);const [scale,setScale]=useState(1);
 const [imports,setImports]=useState<Imported[]>([]);const fileRef=useRef<HTMLInputElement>(null);
 const [character,setCharacter]=useState(scenes.characters[0]);const [background,setBackground]=useState(scenes.backgrounds[0]);const [props,setProps]=useState<string[]>([]);const [vehicle,setVehicle]=useState('None');
 const active=imports[0];
 const chooseMotion=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const format=detect(f.name);if(!format){onStatus?.('Unsupported motion file. Use FBX, glTF, GLB, BVH, VRM or Motion JSON.');return;}let fps=30,duration=0;if(format==='motion-json'||format==='bvh'){try{const text=await f.text();if(format==='motion-json'){const j=JSON.parse(text);fps=Number(j.fps)||30;duration=Number(j.duration)||0}else{const m=text.match(/Frames:\s*(\d+)/i);const ft=text.match(/Frame Time:\s*([\d.]+)/i);const frames=Number(m?.[1]||0);const frameTime=Number(ft?.[1]||1/30);fps=frameTime?1/frameTime:30;duration=frames/fps}}catch{onStatus?.('Motion file read failed.');return;}}
 const item={name:f.name,format,size:f.size,duration,fps};setImports(x=>[item,...x.filter(v=>v.name!==f.name)]);onStatus?.(`${f.name} loaded • ${motionFormatLabels[format]} • ready to retarget`);e.target.value=''};
 const clip=useMemo(()=>active?makeMotionClip(active.name,active.format):null,[active]);
 const exportScene=()=>{const data={version:1,type:'maya-shadow-scene-template',character,background,props,vehicle,createdAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='maya-shadow-scene-template.json';a.click();onStatus?.('Scene template exported');setTimeout(()=>URL.revokeObjectURL(a.href),500)};
 return <div className="motion-studio"><div className="motion-hero"><div><span className="motion-kicker">BEAST MODE • MOTION + SCENE</span><h2>Motion & Scene Builder</h2><p>Bring motion onto a 2D/2.5D rig, then build a story scene with a few clicks.</p></div><div className="motion-badges"><b>Offline</b><b>2D</b><b>2.5D</b><b>3D Motion</b></div></div>
 <div className="motion-tabs"><button className={tab==='motion'?'active':''} onClick={()=>setTab('motion')}>🎞 Motion Retarget</button><button className={tab==='scene'?'active':''} onClick={()=>setTab('scene')}>🎬 Vyond-style Scene Builder</button></div>
 {tab==='motion'?<div className="motion-grid"><section className="motion-card"><h3>1. Import Motion</h3><p>Mixamo FBX, glTF/GLB, BVH, VRM and Maya Shadow Motion JSON are recognised.</p><input ref={fileRef} hidden type="file" accept=".fbx,.gltf,.glb,.bvh,.vrm,.json" onChange={chooseMotion}/><button className="motion-primary" onClick={()=>fileRef.current?.click()}>＋ Import Motion</button>{active&&<div className="motion-file"><strong>{active.name}</strong><span>{motionFormatLabels[active.format]} • {active.fps.toFixed(1)} FPS • {active.duration?`${active.duration.toFixed(2)}s`:'duration from source'}</span></div>}</section>
 <section className="motion-card"><h3>2. Auto Retarget</h3><label>Target<select value={target} onChange={e=>setTarget(e.target.value as MotionTarget)}><option value="2d-bone-rig">2D Bone Rig</option><option value="2.5d-bone-rig">2.5D Bone Rig</option><option value="3d-character">3D Character</option></select></label><label>Scale<input type="number" min="0.01" step="0.05" value={scale} onChange={e=>setScale(Number(e.target.value)||1)}/></label><div className="motion-checks"><label><input type="checkbox" checked={mirror} onChange={e=>setMirror(e.target.checked)}/> Mirror motion</label><label><input type="checkbox" checked={rootMotion} onChange={e=>setRootMotion(e.target.checked)}/> Preserve root motion</label></div>{clip&&<div className="retarget-result">{describeRetarget(clip,target)}<small>Scale {scale.toFixed(2)} • {mirror?'mirrored':'original'} • {rootMotion?'root motion on':'root motion off'}</small></div>}<button disabled={!active} className="motion-primary" onClick={()=>onStatus?.(active?`${active.name} retarget settings applied to ${target}`:'Import a motion first')}>✓ Apply Motion to Selected Character</button></section>
 <section className="motion-card full"><h3>Motion Queue</h3>{imports.length?<div className="motion-list">{imports.map(x=><button key={x.name} className={active?.name===x.name?'selected':''} onClick={()=>setImports([x,...imports.filter(i=>i.name!==x.name)])}><b>{x.name}</b><span>{motionFormatLabels[x.format]}</span></button>)}</div>:<div className="empty-motion">No motion clips yet. Import a clip to start.</div>}<p className="tip">Tip: Mixamo motion is used as motion data; the character art remains your 2D/2.5D asset.</p></section></div>
 :<div className="scene-builder"><section className="scene-card"><h3>1. Character</h3><div className="choice-grid">{scenes.characters.map(x=><button className={character===x?'selected':''} onClick={()=>setCharacter(x)} key={x}>{x}</button>)}</div></section><section className="scene-card"><h3>2. Background</h3><div className="choice-grid">{scenes.backgrounds.map(x=><button className={background===x?'selected':''} onClick={()=>setBackground(x)} key={x}>{x}</button>)}</div></section><section className="scene-card"><h3>3. Props & Vehicles</h3><div className="choice-grid">{scenes.props.map(x=><button className={props.includes(x)?'selected':''} onClick={()=>setProps(p=>p.includes(x)?p.filter(v=>v!==x):[...p,x])} key={x}>{x}</button>)}</div><select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option>None</option>{scenes.vehicles.map(x=><option key={x}>{x}</option>)}</select></section><section className="scene-preview"><span>LIVE SCENE PLAN</span><h2>{character}</h2><p>{background}</p><div>{props.map(p=><b key={p}>{p}</b>)}{vehicle!=='None'&&<b>{vehicle}</b>}</div><button className="motion-primary" onClick={()=>onStatus?.(`Scene ready • ${character} • ${background}`)}>✓ Build Scene</button><button onClick={exportScene}>⇧ Export Scene Template</button></section></div>}
 </div>;
}
