import React,{useMemo,useState} from 'react';
import {CharacterRig} from '../rigging/rigEngine';import {solveTwoBoneIK} from './ikSolver';import {degrees,poseRig} from './bonePose';import {RigPose,poseFromRig} from './poseTrack';import MeshDeformationPreview from './MeshDeformationPreview';import './animationControls.css';

type Props={rig:CharacterRig;frame:number;pose:RigPose;poseFrames:number[];image?:string|null;onPoseChange:(pose:RigPose)=>void;onPoseKeyframe:()=>void;onFrameChange:(frame:number)=>void;onStatus?:(message:string)=>void};
export default function RigPreview({rig,frame,pose,poseFrames,image,onPoseChange,onPoseKeyframe,onFrameChange,onStatus}:Props){
 const [target,setTarget]=useState({x:70,y:58});const [active,setActive]=useState<'L'|'R'>('L');const [onion,setOnion]=useState(true);const [showMesh,setShowMesh]=useState(true);
 const activeUpper=active==='L'?'upperArmL':'upperArmR';const activeLower=active==='L'?'lowerArmL':'lowerArmR';
 const bones=useMemo(()=>poseRig(rig,pose),[rig,pose]);
 const solve=()=>{const root=bones.find(b=>b.id===activeUpper),lower=bones.find(b=>b.id===activeLower);if(!root||!lower)return;const result=solveTwoBoneIK({id:root.id,x:root.x,y:root.y,rotation:root.worldRotation},{x:target.x,y:target.y},root.length,lower.length);const lowerWorld=result.upperRotation+result.lowerRotation;onPoseChange({...pose,[activeUpper]:{rotation:result.upperRotation},[activeLower]:{rotation:lowerWorld}});onStatus?.(`${active} arm IK applied • upper ${degrees(result.upperRotation)}° • lower ${degrees(lowerWorld)}°`)};
 const reset=()=>{onPoseChange(poseFromRig(rig));setTarget({x:70,y:58});onStatus?.('Rig pose reset')};
 const drag=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();setTarget({x:Math.max(5,Math.min(95,((e.clientX-r.left)/r.width)*100)),y:Math.max(5,Math.min(95,((e.clientY-r.top)/r.height)*100))})};
 return <div className="rig-preview-card"><div className="preview-head"><div><b>RIG PREVIEW</b><small>Bone pose / IK / main timeline</small></div><div className="preview-actions"><button className={showMesh?'active':''} onClick={()=>setShowMesh(v=>!v)}>Mesh</button><button className={onion?'active':''} onClick={()=>setOnion(v=>!v)}>Onion</button><button onClick={reset}>Reset</button><button onClick={solve}>Apply IK</button><button onClick={onPoseKeyframe}>◆ Pose Key</button></div></div>{showMesh&&image&&<MeshDeformationPreview rig={rig} pose={pose} image={image}/>}<div className="preview-stage"><svg viewBox="0 0 100 100" preserveAspectRatio="none" onPointerDown={drag}>{onion&&<g opacity=".14" transform="translate(2,0)">{bones.map(b=><line key={'o'+b.id} x1={b.px} y1={b.py} x2={b.x} y2={b.y} stroke="currentColor" strokeWidth="1.1"/>)}</g>}<g>{bones.map(b=><g key={b.id}><line x1={b.px} y1={b.py} x2={b.x} y2={b.y} stroke="currentColor" strokeWidth={b.id==='spine'||b.id==='head'?'2':'1.6'}/><circle cx={b.x} cy={b.y} r={b.id===activeUpper||b.id===activeLower?'2.2':'1.5'}/></g>)}<line x1={bones.find(b=>b.id===activeUpper)?.x??0} y1={bones.find(b=>b.id===activeUpper)?.y??0} x2={target.x} y2={target.y} stroke="currentColor" strokeDasharray="2 2"/><circle className={pose[activeUpper]?'ik-solved':'ik-target'} cx={target.x} cy={target.y} r="3"/></g></svg></div><div className="ik-controls"><button className={active==='L'?'active':''} onClick={()=>setActive('L')}>Left Arm</button><button className={active==='R'?'active':''} onClick={()=>setActive('R')}>Right Arm</button><label>Frame <input type="range" min="1" max="240" value={frame} onChange={e=>onFrameChange(Number(e.target.value))}/><b>{frame}</b></label><label>X <input type="range" min="10" max="90" value={target.x} onChange={e=>setTarget(t=>({...t,x:Number(e.target.value)}))}/><b>{Math.round(target.x)}</b></label><label>Y <input type="range" min="10" max="90" value={target.y} onChange={e=>setTarget(t=>({...t,y:Number(e.target.value)}))}/><b>{Math.round(target.y)}</b></label><span className="ik-status">{poseFrames.length?`POSE KEYS ${poseFrames.join(' • ')}`:'No pose keys yet'}</span></div></div>;
}
