import React,{useMemo,useState} from 'react';
import {CharacterRig} from '../rigging/rigEngine';
import {solveTwoBoneIK} from './ikSolver';
import './animationControls.css';

type Props={rig:CharacterRig;onStatus?:(message:string)=>void};
export default function RigPreview({rig,onStatus}:Props){
 const [target,setTarget]=useState({x:70,y:58});const [active,setActive]=useState<'L'|'R'>('L');const [onion,setOnion]=useState(true);const [solved,setSolved]=useState<{upper:number;lower:number}|null>(null);
 const bones=useMemo(()=>rig.bones.map(b=>{const p=rig.bones.find(x=>x.id===b.parentId);return {...b,px:p?.x??b.x,py:p?.y??b.y}}),[rig]);
 const solve=()=>{const root=rig.bones.find(b=>b.id===(active==='L'?'upperArmL':'upperArmR'));const lower=rig.bones.find(b=>b.id===(active==='L'?'lowerArmL':'lowerArmR'));if(!root||!lower)return;const result=solveTwoBoneIK({x:root.x,y:root.y,rotation:root.rotation},{x:target.x,y:target.y},root.length,lower.length);setSolved({upper:result.upperRotation,lower:result.lowerRotation});onStatus?.(`${active} arm IK solved • upper ${((result.upperRotation*180)/Math.PI).toFixed(1)}° • lower ${((result.lowerRotation*180)/Math.PI).toFixed(1)}°`)};
 const drag=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();setTarget({x:Math.max(5,Math.min(95,((e.clientX-r.left)/r.width)*100)),y:Math.max(5,Math.min(95,((e.clientY-r.top)/r.height)*100))});};
 const activeUpper=active==='L'?'upperArmL':'upperArmR',activeLower=active==='L'?'lowerArmL':'lowerArmR';
 return <div className="rig-preview-card"><div className="preview-head"><div><b>RIG PREVIEW</b><small>IK / motion test</small></div><div className="preview-actions"><button className={onion?'active':''} onClick={()=>setOnion(v=>!v)}>Onion</button><button onClick={solve}>Solve IK</button></div></div><div className="preview-stage"><svg viewBox="0 0 100 100" preserveAspectRatio="none" onPointerDown={drag}>{onion&&<g opacity=".14" transform="translate(2,0)">{bones.map(b=><line key={'o'+b.id} x1={b.px} y1={b.py} x2={b.x} y2={b.y} stroke="currentColor" strokeWidth="1.1"/> )}</g>}<g>{bones.map(b=><g key={b.id}><line x1={b.px} y1={b.py} x2={b.x} y2={b.y} stroke="currentColor" strokeWidth={b.id==='spine'||b.id==='head'?'2':'1.6'}/><circle cx={b.x} cy={b.y} r="1.8"/></g>)}{solved&&<><line x1={rig.bones.find(b=>b.id===activeUpper)?.x??0} y1={rig.bones.find(b=>b.id===activeUpper)?.y??0} x2={target.x} y2={target.y} stroke="currentColor" strokeDasharray="2 2"/><circle className="ik-solved" cx={target.x} cy={target.y} r="2"/></>}<circle className="ik-target" cx={target.x} cy={target.y} r="3"/></g></svg></div><div className="ik-controls"><button className={active==='L'?'active':''} onClick={()=>{setActive('L');setSolved(null)}}>Left Arm</button><button className={active==='R'?'active':''} onClick={()=>{setActive('R');setSolved(null)}}>Right Arm</button><label>X <input type="range" min="10" max="90" value={target.x} onChange={e=>{setTarget(t=>({...t,x:Number(e.target.value)}));setSolved(null)}}/><b>{Math.round(target.x)}</b></label><label>Y <input type="range" min="10" max="90" value={target.y} onChange={e=>{setTarget(t=>({...t,y:Number(e.target.value)}));setSolved(null)}}/><b>{Math.round(target.y)}</b></label><span className="ik-status">Target {active} • {solved?'Solved':'Drag target / Solve IK'}</span></div></div>;
}
