import React,{useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import RigMapCanvas from './rigging/RigMapCanvas';
import FaceRigPanel from './rigging/FaceRigPanel';
import {CharacterRig} from './rigging/rigEngine';
import {createDefaultProject,StudioProject,addKeyframe} from './project/projectModel';
import './styles.css';import './rigging/rigMap.css';import './rigging/rigEngine.css';
const tools=[['V','Select'],['B','Brush'],['P','Pen'],['E','Eraser'],['T','Text'],['M','Move'],['R','Rectangle'],['O','Ellipse']];
const workspaces=['Animation','Character','Background','Audio/Video'];
function downloadJson(name:string,data:unknown){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function App(){
 const [workspace,setWorkspace]=useState('Animation'),[image,setImage]=useState<string|null>(null),[zoom,setZoom]=useState(100),[playing,setPlaying]=useState(false),[frame,setFrame]=useState(1),[project,setProject]=useState<StudioProject>(createDefaultProject),[rig,setRig]=useState<CharacterRig|null>(null),[inspector,setInspector]=useState<'properties'|'face'>('properties'),[tool,setTool]=useState('Select'),[status,setStatus]=useState('Ready');
 const inputRef=useRef<HTMLInputElement>(null);const rigFileRef=useRef<HTMLInputElement>(null);
 const scene=project.scenes.find(s=>s.id===project.activeSceneId)!;
 const importCharacter=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{setImage(String(r.result));setWorkspace('Character');setStatus('Character imported • ready for rig mapping')};r.readAsDataURL(f)};
 const addTimelineKey=()=>{const track=scene.tracks.find(t=>t.kind==='character');if(!track)return;const next=addKeyframe(scene,track.id,frame,'transform',{x:50,y:50,rotation:0,scale:1});setProject(p=>({...p,updatedAt:new Date().toISOString(),scenes:p.scenes.map(s=>s.id===scene.id?next:s)}));setStatus(`Keyframe created at frame ${frame}`)};
 const createScene=()=>{const next={...createDefaultProject().scenes[0],name:`Scene ${String(project.scenes.length+1).padStart(2,'0')}`};setProject(p=>({...p,activeSceneId:next.id,scenes:[...p.scenes,next],updatedAt:new Date().toISOString()}));setFrame(1);setStatus('New scene created')};
 const exportProject=()=>downloadJson(`${project.name.replace(/\s+/g,'-').toLowerCase()}.maya.json`,project);
 const exportRig=()=>rig&&downloadJson('character-rig.mayarig.json',rig);
 const importRig=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setRig(JSON.parse(String(r.result)));setStatus('Rig template imported')}catch{setStatus('Invalid rig JSON')}};r.readAsText(f)};
 return <div className="studio">
 <header className="topbar"><div className="brand"><span className="brand-mark">M</span><div><strong>Maya Shadow</strong><small>Animation Studio</small></div></div><nav className="menus">{['File','Edit','View','Insert','Animate','Character','AI Tools','Export'].map(x=><span key={x}>{x}</span>)}</nav><div className="top-actions"><button onClick={exportProject}>Save Project</button><button onClick={()=>setStatus('Undo stack ready for next engine pass')}>Undo</button><button className="primary" onClick={()=>setPlaying(v=>!v)}>{playing?'Stop':'Preview'}</button></div></header>
 <section className="toolbar"><div className="tool-group"><span className="group-label">Workspace</span>{workspaces.map(x=><button key={x} className={workspace===x?'active':''} onClick={()=>setWorkspace(x)}>{x}</button>)}</div><div className="tool-group"><span className="group-label">Zoom</span><button onClick={()=>setZoom(z=>Math.max(25,z-25))}>−</button><span className="zoom">{zoom}%</span><button onClick={()=>setZoom(z=>Math.min(300,z+25))}>+</button></div><div className="tool-group"><span className="group-label">Tool</span><strong className="tool-readout">{tool}</strong></div></section>
 <main className="workspace"><aside className="left-panel"><div className="panel-title">TOOLS</div><div className="tools-grid">{tools.map(([k,l])=><button key={k} title={l} className={tool===l?'selected-tool':''} onClick={()=>setTool(l)}><b>{k}</b><span>{l}</span></button>)}</div><div className="panel-title section">CHARACTER PIPELINE</div><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={importCharacter}/><input ref={rigFileRef} type="file" accept="application/json,.mayarig.json" hidden onChange={importRig}/><button className="wide" onClick={()=>inputRef.current?.click()}>＋ Import Character</button><button className="wide" onClick={()=>setWorkspace('Character')}>✦ Auto Rig Map</button><button className="wide" onClick={()=>setWorkspace('Character')}>◎ Rig Editor</button><button className="wide" onClick={()=>rigFileRef.current?.click()}>⇩ Import Rig Template</button><button className="wide" onClick={exportRig} disabled={!rig}>⇧ Export Rig Template</button><div className="panel-title section">PRODUCTION</div><button className="wide" onClick={createScene}>＋ New Scene</button><button className="wide">▣ Asset Library</button><button className="wide">◉ Camera</button></aside>
 <section className="canvas-area"><div className="canvas-tabs"><span className="tab active">{scene.name}</span><span className="tab" onClick={createScene}>+ New Scene</span></div>{workspace==='Character'?<RigMapCanvas image={image} onRigCreated={setRig}/>:<div className="stage-wrap"><div className="stage" style={{transform:`scale(${zoom/100})`}}>{image?<img src={image} alt="Imported character" className="character-image"/>:<><div className="stage-cross">+</div><div className="stage-label">CANVAS<br/><small>{scene.width} × {scene.height}</small></div></>}</div></div>}</section>
 <aside className="right-panel"><div className="inspector-tabs"><button className={inspector==='properties'?'active':''} onClick={()=>setInspector('properties')}>Properties</button><button className={inspector==='face'?'active':''} onClick={()=>setInspector('face')}>Face Rig</button></div>{inspector==='face'?<FaceRigPanel/>:<><div className="panel-title">PROPERTIES</div><div className="property-card"><h3>{image?'Imported Character':'Selection'}</h3><p>{image?'Character loaded • Ready for rig mapping':'No object selected'}</p>{image&&<div className="property-row"><span>Zoom</span><strong>{zoom}%</strong></div>}{rig&&<div className="property-row"><span>Rig</span><strong>{rig.bones.length} bones</strong></div>}</div><div className="panel-title section">LAYERS</div>{['Scene','Character','Rig Controls','Background'].map((x,i)=><div className={`layer ${i===0?'active':''}`} key={x}><span>{i<2?'◉':'◇'}</span><b>{x}</b><i>{i<2?'Visible':''}</i></div>)}<div className="panel-title section">ASSETS</div><div className="asset-grid"><div>Characters</div><div>Props</div><div>Backgrounds</div><div>Audio</div></div></>}</aside></main>
 <section className="timeline"><div className="timeline-head"><div><b>TIMELINE</b><span> {scene.name}</span></div><div className="transport"><button onClick={()=>setFrame(Math.max(1,frame-1))}>◀</button><button className="play" onClick={()=>setPlaying(v=>!v)}>{playing?'■':'▶'}</button><button onClick={()=>setFrame(Math.min(scene.duration,frame+1))}>▶</button><span>F {frame} / {scene.duration}</span></div><div><button onClick={addTimelineKey}>＋ Keyframe</button><button onClick={()=>setFrame(1)}>⏮</button></div></div><div className="timeline-body"><div className="track-labels">{scene.tracks.map(t=><div key={t.id}>{t.name}</div>)}</div><div className="tracks"><div className="ruler">{Array.from({length:12},(_,i)=><span key={i}>{i+1}</span>)}</div>{scene.tracks.map(t=><div className="track" key={t.id}>{t.keyframes.map(k=><button className="keyframe" key={k.id} style={{left:`${Math.max(8,k.frame*3)}px`}} title={`${k.property} • frame ${k.frame}`} onClick={()=>setFrame(k.frame)}/>)}</div>)}</div></div></section>
 <footer><span>● {status}</span><span>Maya Shadow Animation Studio • Professional 2D/2.5D Pipeline</span><span>{scene.fps} FPS • {scene.width}×{scene.height}</span></footer></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
