import React,{useEffect,useRef,useState,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import RigMapCanvas from './rigging/RigMapCanvas';import FaceRigPanel from './rigging/FaceRigPanel';import FaceAnimationPanel from './rigging/FaceAnimationPanel';import FaceAnimationPreview from './rigging/FaceAnimationPreview';import RigPreview from './animation/RigPreview';import MeshDeformationPreview from './animation/MeshDeformationPreview';import DrawingWorkspace from './drawing/DrawingWorkspace';import CameraPanel from './camera/CameraPanel';import PresetLibrary from './presets/PresetLibrary';
import {defaultCamera,Camera2D} from './camera/cameraModel';import {CharacterRig} from './rigging/rigEngine';import {FaceAnimationValues,defaultFaceAnimation} from './rigging/faceAnimationModel';import {faceValuesAtFrame} from './animation/faceTrack';
import {createDefaultProject,StudioProject,addKeyframe,removeKeyframe,duplicateKeyframe,setKeyframeEasing,Asset,makeId,Keyframe} from './project/projectModel';import {readMediaFile} from './media/mediaModel';import {interpolateMotion,motionFromTrack} from './animation/motionTrack';import {RigPose,interpolatePose,poseFromRig,poseFromTrackValue,poseToTrackValue} from './animation/poseTrack';import {StudioPreset} from './presets/presetModel';
import AudioVideoStudioPanel from './media/AudioVideoStudioPanel';
import AIProductionWorkspace from './ai/AIProductionWorkspace';import {saveRecoverySnapshot,migrateProject,loadLatestRecoverySnapshot} from './project/projectStorage';import {replaceCharacterAsset} from './character/characterReplacement';import {installRenderFrameBridge} from './export/renderBridge';
import './styles.css';import './rigging/rigMap.css';import './rigging/rigEngine.css';import './drawing/drawing.css';import './rigging/faceAnimation.css';import './rigging/faceAnimationPreview.css';
const tools=[['V','Select'],['B','Brush'],['P','Pen'],['E','Eraser'],['T','Text'],['M','Move'],['R','Rectangle'],['O','Ellipse']];const workspaces=['Animation','Character','Background','Presets','Audio/Video','AI','Drawing'];
function downloadJson(name:string,data:unknown){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function App(){
 const [workspace,setWorkspace]=useState('Animation'),[image,setImage]=useState<string|null>(null),[zoom,setZoom]=useState(100),[playing,setPlaying]=useState(false),[frame,setFrame]=useState(1),[project,setProject]=useState<StudioProject>(createDefaultProject),[rig,setRig]=useState<CharacterRig|null>(null),[inspector,setInspector]=useState<'properties'|'face'|'camera'>('properties'),[tool,setTool]=useState('Select'),[status,setStatus]=useState('Ready'),[assets,setAssets]=useState<Asset[]>([]),[selectedLayer,setSelectedLayer]=useState('Character'),[camera,setCamera]=useState<Camera2D>(defaultCamera),[faceEdit,setFaceEdit]=useState<FaceAnimationValues>(defaultFaceAnimation),[selectedKeyframeId,setSelectedKeyframeId]=useState<string|null>(null);
 const inputRef=useRef<HTMLInputElement>(null),rigFileRef=useRef<HTMLInputElement>(null),mediaRef=useRef<HTMLInputElement>(null),bgRef=useRef<HTMLInputElement>(null);const scene=project.scenes.find(s=>s.id===project.activeSceneId)!;
 const characterTrack=scene.tracks.find(t=>t.kind==='character');const faceTrack=scene.tracks.find(t=>t.kind==='face');const rigTrack=scene.tracks.find(t=>t.kind==='rig');const motion=characterTrack?interpolateMotion(motionFromTrack(characterTrack.keyframes),frame):{x:0,y:0,rotation:0,scale:1};const face=faceTrack?faceValuesAtFrame(faceTrack.keyframes,frame):faceEdit;
 const rigKeys=useMemo(()=>rigTrack?rigTrack.keyframes.filter(k=>k.property==='pose').map(k=>({frame:k.frame,pose:poseFromTrackValue(k.value)})).sort((a,b)=>a.frame-b.frame):[],[rigTrack]);const rigPose=useMemo(()=>rig?(rigKeys.length?interpolatePose(rigKeys,frame):poseFromRig(rig)): {},[rig,rigKeys,frame]);
 const selectedKeyframe=useMemo(()=>{if(!selectedKeyframeId)return null;for(const t of scene.tracks){const k=t.keyframes.find(x=>x.id===selectedKeyframeId);if(k)return {track:t,keyframe:k}}return null},[scene,selectedKeyframeId]);
 useEffect(()=>{if(!selectedKeyframeId)return;const exists=scene.tracks.some(t=>t.keyframes.some(k=>k.id===selectedKeyframeId));if(!exists)setSelectedKeyframeId(null)},[scene,selectedKeyframeId]);
 useEffect(()=>{let cancelled=false;(async()=>{const restored=await loadLatestRecoverySnapshot();if(cancelled||!restored)return;setProject(restored);setAssets(restored.assets||[]);const character=restored.assets?.find(a=>a.type==='character');if(character?.source)setImage(character.source);setFrame(1);setStatus('Recovered latest project snapshot automatically')})();return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setFrame(f=>f>=scene.duration?1:f+1),1000/scene.fps);return()=>clearInterval(id)},[playing,scene.duration,scene.fps]);
 useEffect(()=>{let timer:number|undefined;const save=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{saveRecoverySnapshot({...project,assets}).catch(()=>{});},1000)};save();return()=>window.clearTimeout(timer)},[project,assets]);
 useEffect(()=>{const restore=(event:Event)=>{const detail=(event as CustomEvent<StudioProject>).detail;if(!detail)return;const restored=migrateProject(detail);setProject(restored);setAssets(restored.assets||[]);const character=restored.assets?.find(a=>a.type==='character');if(character?.source)setImage(character.source);setFrame(1);setWorkspace('Animation');setStatus('Project restored from recovery snapshot')};window.addEventListener('maya-shadow:restore-project',restore);return()=>window.removeEventListener('maya-shadow:restore-project',restore)},[]);
 useEffect(()=>installRenderFrameBridge(setFrame),[]);
 const importCharacter=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const src=String(r.result);const replacement:Asset={id:makeId('asset'),name:f.name,type:'character',source:src,createdAt:new Date().toISOString()};const result=replaceCharacterAsset(assets,replacement,src);setImage(result.image);setAssets(result.assets);setWorkspace('Character');setStatus(rig?'Character replaced • rig and timeline preserved':'Character imported • ready for rig mapping')};r.readAsDataURL(f)};
 const importBackground=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const src=String(r.result);setAssets(a=>[...a,{id:makeId('asset'),name:f.name,type:'background',source:src,createdAt:new Date().toISOString()}]);setWorkspace('Background');setStatus('Background imported')};r.readAsDataURL(f)};
 const importMedia=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const m=await readMediaFile(f);setAssets(a=>[...a,{id:m.id,name:m.name,type:m.type,source:m.source,createdAt:new Date().toISOString()}]);setWorkspace('Audio/Video');setStatus(`${m.type==='audio'?'Audio':'Video'} imported • ${m.duration.toFixed(1)}s`)};
 const updateScene=(next:typeof scene)=>setProject(p=>({...p,updatedAt:new Date().toISOString(),scenes:p.scenes.map(s=>s.id===scene.id?next:s)}));
 const addTimelineKey=()=>{if(!characterTrack)return;const next=addKeyframe(scene,characterTrack.id,frame,'transform',{x:motion.x,y:motion.y,rotation:motion.rotation,scale:motion.scale});const key=next.tracks.find(t=>t.id===characterTrack.id)?.keyframes.find(k=>k.frame===frame&&k.property==='transform');updateScene(next);if(key)setSelectedKeyframeId(key.id);setStatus(`Character keyframe created at frame ${frame}`)};
 const addFaceKey=(property:keyof FaceAnimationValues,value:number)=>{if(!faceTrack)return;const next=addKeyframe(scene,faceTrack.id,frame,property,value);const key=next.tracks.find(t=>t.id===faceTrack.id)?.keyframes.find(k=>k.frame===frame&&k.property===property);updateScene(next);if(key)setSelectedKeyframeId(key.id);setStatus(`Face keyframe • ${property} • frame ${frame}`)};
 const updateFace=(v:FaceAnimationValues)=>{setFaceEdit(v);if(!faceTrack||!faceTrack.keyframes.length)setStatus('Facial controls live • press ◆ to keyframe')};
 const updateRigPose=(pose:RigPose)=>{if(!rigTrack)return;const value=poseToTrackValue(pose);const next=addKeyframe(scene,rigTrack.id,frame,'pose',value);updateScene(next)};
 const addRigPoseKey=()=>{if(!rig||!rigTrack)return;const value=poseToTrackValue(rigPose);const next=addKeyframe(scene,rigTrack.id,frame,'pose',value);const key=next.tracks.find(t=>t.id===rigTrack.id)?.keyframes.find(k=>k.frame===frame&&k.property==='pose');updateScene(next);if(key)setSelectedKeyframeId(key.id);setStatus(`Rig pose keyframe created at frame ${frame}`)};
 const applyMotionFrames=(frames:Array<{frame:number;pose:RigPose}>,meta:{source:string;fps:number;target:string;scale:number;mirror:boolean;rootMotion:boolean})=>{if(!rig){setStatus('Import or create a character rig first, then apply the motion.');setWorkspace('Character');return;}if(!rigTrack){setStatus('Rig Controls track is unavailable in the active scene.');return;}let next=scene;for(const item of frames){if(item.frame>scene.duration)break;next=addKeyframe(next,rigTrack.id,Math.max(1,item.frame),'pose',poseToTrackValue(item.pose));}updateScene(next);setWorkspace('Character');setFrame(Math.max(1,Math.min(scene.duration,frames[0]?.frame||1)));setSelectedLayer('Rig Controls');setStatus(`Motion applied to rig timeline • ${frames.length} pose keyframes • ${meta.source}`)};
 const deleteSelectedKeyframe=()=>{if(!selectedKeyframe)return;updateScene(removeKeyframe(scene,selectedKeyframe.track.id,selectedKeyframe.keyframe.id));setSelectedKeyframeId(null);setStatus(`Keyframe deleted • frame ${selectedKeyframe.keyframe.frame}`)};
 const duplicateSelectedKeyframe=()=>{if(!selectedKeyframe)return;const next=duplicateKeyframe(scene,selectedKeyframe.track.id,selectedKeyframe.keyframe.id,frame);const key=next.tracks.find(t=>t.id===selectedKeyframe.track.id)?.keyframes.find(k=>k.frame===frame&&k.property===selectedKeyframe.keyframe.property);updateScene(next);if(key)setSelectedKeyframeId(key.id);setStatus(`Keyframe duplicated to frame ${frame}`)};
 const changeSelectedEasing=(easing:NonNullable<Keyframe['easing']>)=>{if(!selectedKeyframe)return;updateScene(setKeyframeEasing(scene,selectedKeyframe.track.id,selectedKeyframe.keyframe.id,easing));setStatus(`Easing changed to ${easing}`)};
 const createScene=()=>{const base=createDefaultProject().scenes[0];const next={...base,id:makeId('scene'),name:`Scene ${String(project.scenes.length+1).padStart(2,'0')}`};setProject(p=>({...p,activeSceneId:next.id,scenes:[...p.scenes,next],updatedAt:new Date().toISOString()}));setFrame(1);setStatus('New scene created');};
 const exportProject=()=>{saveRecoverySnapshot({...project,assets}).catch(()=>{});downloadJson(`${project.name.replace(/\s+/g,'-').toLowerCase()}.maya.json`,{...project,assets})};const exportRig=()=>rig&&downloadJson('character-rig.mayarig.json',rig);
 const importRig=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setRig(JSON.parse(String(r.result)));setStatus('Rig template imported')}catch{setStatus('Invalid rig JSON')}};r.readAsText(f)};const assetFor=(type:Asset['type'])=>assets.filter(a=>a.type===type);const renderTransform={transform:`translate(${motion.x}px,${motion.y}px) rotate(${motion.rotation}deg) scale(${motion.scale})`};
 const usePreset=(p:StudioPreset)=>{if(p.category==='character'&&p.sourceType==='image'&&p.source){const replacement:Asset={id:makeId('asset'),name:p.name,type:'character',source:p.source,createdAt:new Date().toISOString()};const result=replaceCharacterAsset(assets,replacement,p.source);setImage(result.image);setAssets(result.assets);setWorkspace('Character');setStatus(rig?`Character replaced with ${p.name} • rig and timeline preserved`:`${p.name} selected • ready for rig mapping`)}else if(p.category==='background'&&p.sourceType==='image'&&p.source){setAssets(a=>[...a,{id:makeId('asset'),name:p.name,type:'background',source:p.source!,createdAt:new Date().toISOString()}]);setWorkspace('Background')}else{setStatus(`${p.name} preset selected • ready for its workflow`)} };
 return <div className="studio"><header className="topbar"><div className="brand"><span className="brand-mark">M</span><div><strong>Maya Shadow</strong><small>Animation Studio</small></div></div><nav className="menus">{['File','Edit','View','Insert','Animate','Character','AI Tools','Export'].map(x=><span key={x}>{x}</span>)}</nav><div className="top-actions"><button onClick={exportProject}>Save Project</button><button onClick={()=>setWorkspace('Presets')}>Preset Library</button><button onClick={()=>setStatus('Undo stack ready')}>Undo</button><button className="primary" onClick={()=>setPlaying(v=>!v)}>{playing?'Stop':'Preview'}</button></div></header>
 <section className="toolbar"><div className="tool-group"><span className="group-label">Workspace</span>{workspaces.map(x=><button key={x} className={workspace===x?'active':''} onClick={()=>setWorkspace(x)}>{x}</button>)}</div><div className="tool-group"><span className="group-label">Zoom</span><button onClick={()=>setZoom(z=>Math.max(25,z-25))}>−</button><span className="zoom">{zoom}%</span><button onClick={()=>setZoom(z=>Math.min(300,z+25))}>+</button></div><div className="tool-group"><span className="group-label">Tool</span><strong className="tool-readout">{tool}</strong></div></section>
 <main className="workspace"><aside className="left-panel"><div className="panel-title">TOOLS</div><div className="tools-grid">{tools.map(([k,l])=><button key={k} title={l} className={tool===l?'selected-tool':''} onClick={()=>{setTool(l);setStatus(`${l} tool selected`)}}><b>{k}</b><span>{l}</span></button>)}</div><div className="panel-title section">CHARACTER PIPELINE</div><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={importCharacter}/><input ref={rigFileRef} type="file" accept="application/json,.mayarig.json" hidden onChange={importRig}/><button className="wide" onClick={()=>inputRef.current?.click()}>＋ Import Character</button><button className="wide" onClick={()=>setWorkspace('Character')}>✦ Auto Rig Map</button><button className="wide" onClick={()=>setWorkspace('Character')}>◎ Rig Editor</button><button className="wide" onClick={()=>rigFileRef.current?.click()}>⇩ Import Rig Template</button><button className="wide" onClick={exportRig} disabled={!rig}>⇧ Export Rig Template</button><div className="panel-title section">PRODUCTION</div><input ref={bgRef} type="file" accept="image/*" hidden onChange={importBackground}/><input ref={mediaRef} type="file" accept="audio/*,video/*" hidden onChange={importMedia}/><button className="wide" onClick={createScene}>＋ New Scene</button><button className="wide" onClick={()=>setWorkspace('Background')}>▣ Asset Library</button><button className="wide" onClick={()=>setWorkspace('Presets')}>✦ Preset Library</button><button className="wide" onClick={()=>bgRef.current?.click()}>▧ Import Background</button><button className="wide" onClick={()=>mediaRef.current?.click()}>♫ Import Audio / Video</button><button className="wide" onClick={()=>setWorkspace('Audio/Video')}>🎚 Professional Audio / Video</button><button className="wide" onClick={()=>setWorkspace('AI')}>🧠 AI Production Center</button><button className="wide" onClick={()=>setWorkspace('Drawing')}>✎ Drawing Studio</button></aside>
 <section className="canvas-area"><div className="canvas-tabs"><span className="tab active">{workspace==='Presets'?'Preset Library':scene.name}</span>{workspace!=='Presets'&&<span className="tab" onClick={createScene}>+ New Scene</span>}</div>{workspace==='Presets'?<PresetLibrary onUse={usePreset} onStatus={setStatus} onApplyMotion={applyMotionFrames}/>:workspace==='Character'?<div className="character-workspace">{rig?<><RigPreview rig={rig} frame={frame} pose={rigPose} poseFrames={rigKeys.map(k=>k.frame)} onPoseChange={updateRigPose} onPoseKeyframe={addRigPoseKey} onFrameChange={setFrame} onStatus={setStatus}/><MeshDeformationPreview rig={rig} pose={rigPose} image={image}/></>:<RigMapCanvas image={image} onRigCreated={setRig}/>}<FaceAnimationPreview values={face} image={image}/></div>:workspace==='Drawing'?<DrawingWorkspace onStatus={setStatus}/>:workspace==='Background'?<div className="asset-workspace"><div className="workspace-title">BACKGROUND & ENVIRONMENT</div><div className="asset-large-grid">{assetFor('background').map(a=><button key={a.id} onClick={()=>setStatus(`Background selected: ${a.name}`)}><img src={a.source}/><span>{a.name}</span></button>)}<button className="asset-empty" onClick={()=>bgRef.current?.click()}>＋ Add Background</button></div></div>:workspace==='Audio/Video'?<AudioVideoStudioPanel assets={assets} onImport={()=>mediaRef.current?.click()} onStatus={setStatus}/>:workspace==='AI'?<AIProductionWorkspace onWorkspaceChange={setWorkspace} onPreview={()=>setPlaying(true)} onStatus={setStatus}/>:<div className="stage-wrap"><div className="stage" style={{transform:`scale(${zoom/100})`}}><div className="camera-frame" style={{transform:`translate(${-camera.x}px,${-camera.y}px) scale(${camera.zoom}) rotate(${-camera.rotation}deg)`}}>{image?<img src={image} alt="Imported character" className="character-image" style={renderTransform}/>:<><div className="stage-cross">+</div><div className="stage-label">CANVAS<br/><small>{scene.width} × {scene.height}</small></div></>}</div></div></div>}</section>
 <aside className="right-panel"><div className="inspector-tabs"><button className={inspector==='properties'?'active':''} onClick={()=>setInspector('properties')}>Properties</button><button className={inspector==='face'?'active':''} onClick={()=>setInspector('face')}>Face Rig</button><button className={inspector==='camera'?'active':''} onClick={()=>setInspector('camera')}>Camera</button></div>{inspector==='face'?<><FaceAnimationPanel values={face} onChange={updateFace} onKeyframe={addFaceKey}/><FaceRigPanel values={face} onChange={updateFace} onKeyframe={addFaceKey}/><FaceAnimationPreview values={face} image={image}/></>:inspector==='camera'?<CameraPanel camera={camera} onChange={setCamera}/>:<><div className="panel-title">PROPERTIES</div><div className="property-card"><h3>{selectedLayer}</h3><p>{image?'Character asset loaded':'No object selected'}</p>{rig&&<div className="property-row"><span>Rig</span><strong>{rig.bones.length} bones</strong></div>}<div className="property-row"><span>Frame Transform</span><strong>{Math.round(motion.x)}, {Math.round(motion.y)}</strong></div><div className="property-row"><span>Face Track</span><strong>{faceTrack?.keyframes.length??0} keys</strong></div><div className="property-row"><span>Rig Pose Track</span><strong>{rigTrack?.keyframes.filter(k=>k.property==='pose').length??0} keys</strong></div>{rig&&<div className="property-row"><span>Mesh</span><strong>Grid deformation ready</strong></div>}</div><div className="panel-title section">LAYERS</div>{['Scene','Character','Eyes / Face','Mouth / Phonemes','Rig Controls','Background'].map((x,i)=><button className={`layer ${selectedLayer===x?'active':''}`} key={x} onClick={()=>setSelectedLayer(x)}><span>{i<2?'◉':'◇'}</span><b>{x}</b><i>{i<2?'Visible':''}</i></button>)}<div className="panel-title section">ASSETS ({assets.length})</div><div className="asset-grid"><div>Characters {assetFor('character').length}</div><div>Props</div><div>Backgrounds {assetFor('background').length}</div><div>Audio {assetFor('audio').length}</div></div></>}</aside></main>
 <section className="timeline"><div className="timeline-head"><div><b>TIMELINE</b><span> {scene.name}</span></div><div className="transport"><button onClick={()=>setFrame(Math.max(1,frame-1))}>◀</button><button className="play" onClick={()=>setPlaying(v=>!v)}>{playing?'■':'▶'}</button><button onClick={()=>setFrame(Math.min(scene.duration,frame+1))}>▶</button><span>F {frame} / {scene.duration}</span></div><div className="timeline-edit-tools"><button onClick={addTimelineKey}>＋ Keyframe</button><button onClick={deleteSelectedKeyframe} disabled={!selectedKeyframe}>Delete</button><button onClick={duplicateSelectedKeyframe} disabled={!selectedKeyframe}>Duplicate to Current</button><select value={selectedKeyframe?.keyframe.easing||'linear'} disabled={!selectedKeyframe} onChange={e=>changeSelectedEasing(e.target.value as NonNullable<Keyframe['easing']>)} aria-label="Keyframe easing"><option value="linear">Linear</option><option value="ease-in">Ease In</option><option value="ease-out">Ease Out</option><option value="ease-in-out">Ease In Out</option></select><button onClick={()=>setFrame(1)}>⏮</button></div></div><div className="timeline-body"><div className="track-labels">{scene.tracks.map(t=><div key={t.id}>{t.name}</div>)}</div><div className="tracks"><div className="ruler">{Array.from({length:12},(_,i)=><span key={i}>{i+1}</span>)}</div>{scene.tracks.map(t=><div className="track" key={t.id}>{t.keyframes.map(k=><button className={`keyframe ${selectedKeyframeId===k.id?'selected':''}`} key={k.id} style={{left:`${Math.max(8,k.frame*3)}px`}} title={`${k.property} • frame ${k.frame} • ${k.easing||'linear'}`} onClick={()=>{setSelectedKeyframeId(k.id);setFrame(k.frame);setStatus(`Selected ${k.property} keyframe • frame ${k.frame}`)}}/>)}</div>)}</div></div></section>
 <footer><span>{status}</span><span>Scene {scene.width}×${scene.height} • {scene.fps} FPS • {Math.round((frame/scene.fps)*10)/10}s</span></footer></div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
