import React,{useEffect,useRef,useState,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import RigMapCanvas from './rigging/RigMapCanvas';import FaceRigPanel from './rigging/FaceRigPanel';import FaceAnimationPanel from './rigging/FaceAnimationPanel';import FaceAnimationPreview from './rigging/FaceAnimationPreview';import RigPreview from './animation/RigPreview';import MeshDeformationPreview from './animation/MeshDeformationPreview';import DrawingWorkspace from './drawing/DrawingWorkspace';import CameraPanel from './camera/CameraPanel';import PresetLibrary from './presets/PresetLibrary';
import {defaultCamera,Camera2D} from './camera/cameraModel';import {CharacterRig} from './rigging/rigEngine';import {FaceAnimationValues,defaultFaceAnimation} from './rigging/faceAnimationModel';import {faceValuesAtFrame} from './animation/faceTrack';
import {createDefaultProject,StudioProject,SceneSetup,addKeyframe,removeKeyframe,duplicateKeyframe,setKeyframeEasing,Asset,makeId,Keyframe} from './project/projectModel';import {readMediaFile} from './media/mediaModel';import {interpolateMotion,motionFromTrack} from './animation/motionTrack';import {RigPose,interpolatePose,poseFromRig,poseFromTrackValue,poseToTrackValue} from './animation/poseTrack';import {StudioPreset} from './presets/presetModel';
import AudioVideoStudioPanel from './media/AudioVideoStudioPanel';
import AIProductionWorkspace from './ai/AIProductionWorkspace';import {saveRecoverySnapshot,migrateProject,loadLatestRecoverySnapshot} from './project/projectStorage';import {replaceCharacterAsset} from './character/characterReplacement';import {installRenderFrameBridge} from './export/renderBridge';
import './styles.css';import './rigging/rigMap.css';import './rigging/rigEngine.css';import './drawing/drawing.css';import './rigging/faceAnimation.css';import './rigging/faceAnimationPreview.css';
const tools=[['V','Select'],['B','Brush'],['P','Pen'],['E','Eraser'],['T','Text'],['M','Move'],['R','Rectangle'],['O','Ellipse']];const workspaces=['Animation','Character','Background','Presets','Audio/Video','AI','Drawing'];
function svgAsset(svg:string){return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
function makePresetCharacter(name:string){
 const female=/female|woman|mother/i.test(name),child=/child/i.test(name),elder=/elder/i.test(name),ghost=/ghost|shadow/i.test(name);
 const shirt=ghost?'#d8dbe5':female?'#b94754':child?'#e1b34c':elder?'#8a9b75':'#d9d0bd';
 const pants=ghost?'#4b5063':female?'#285b78':'#394b3a';
 const height=child?0.82:elder?1.02:1;
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="500" height="760" viewBox="0 0 500 760"><defs><linearGradient id="skin" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#d99c75"/><stop offset="1" stop-color="#a9674b"/></linearGradient><linearGradient id="cloth" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${shirt}"/><stop offset="1" stop-color="${shirt}" stop-opacity=".72"/></linearGradient></defs><ellipse cx="250" cy="724" rx="112" ry="18" fill="#302820" opacity=".16"/><g transform="translate(0 ${Math.round(110*(1-height))}) scale(1 ${height})"><path d="M205 477 L176 663 Q175 683 198 684 L224 683 L250 526 L276 683 L305 684 Q325 681 320 659 L295 477Z" fill="${pants}" stroke="#302c29" stroke-width="5"/><path d="M184 663 Q205 654 225 668 L225 695 L170 695 Q160 686 184 663 M276 668 Q298 654 318 663 L333 690 Q330 698 315 696 L275 696Z" fill="#47362a"/><path d="M177 286 Q204 265 250 267 Q296 265 323 286 L307 482 Q250 511 193 482Z" fill="url(#cloth)" stroke="#4a4036" stroke-width="6"/><path d="M210 282 L250 329 L290 282" fill="none" stroke="#f3e6d1" stroke-width="9" opacity=".8"/><path d="M190 303 L153 418 Q150 433 167 440 L183 438 L218 355 M310 303 L347 418 Q350 433 333 440 L317 438 L282 355" fill="url(#cloth)" stroke="#4a4036" stroke-width="6" stroke-linejoin="round"/><path d="M152 417 Q145 435 163 446 L180 440 L176 420Z M347 417 Q355 435 337 446 L320 440 L324 420Z" fill="url(#skin)"/><rect x="229" y="238" width="42" height="55" rx="16" fill="url(#skin)"/><ellipse cx="250" cy="177" rx="73" ry="91" fill="url(#skin)" stroke="#6e4535" stroke-width="5"/><path d="M178 174 Q166 95 231 82 Q304 68 325 137 L319 171 Q304 133 279 126 Q239 147 186 132Z" fill="#211d1b"/><path d="M188 175 Q202 163 221 174 M278 174 Q297 162 312 174" fill="none" stroke="#30221e" stroke-width="7" stroke-linecap="round"/><ellipse cx="211" cy="190" rx="8" ry="11" fill="#211d1b"/><ellipse cx="289" cy="190" rx="8" ry="11" fill="#211d1b"/><path d="M250 190 L241 218 L256 220" fill="none" stroke="#8a503c" stroke-width="5" stroke-linecap="round"/><path d="M226 240 Q250 251 274 239" fill="none" stroke="#773d34" stroke-width="5" stroke-linecap="round"/><path d="M191 143 Q218 120 250 137 Q281 118 309 144" fill="none" stroke="#211d1b" stroke-width="11" stroke-linecap="round"/>${female?'<path d="M181 154 Q145 196 171 263 L191 294 L199 231Z M319 154 Q355 196 329 263 L309 294 L301 231Z" fill="#211d1b"/>':''}<path d="M204 294 L250 323 L296 294" fill="none" stroke="#a69a83" stroke-width="4" opacity=".7"/></g></svg>`;
 return svgAsset(svg)
}
function makePresetBackground(name:string){
 const night=/night|haunted|horror|forest/i.test(name),river=/river/i.test(name),room=/interior|room/i.test(name),market=/market|tea stall/i.test(name);
 const sky=night?'#151b31':river?'#e7a46b':'#8ec7df',ground=night?'#27302c':river?'#78634a':'#8ba65b';
 const scene=room
 ?'<rect x="0" y="0" width="1920" height="1080" fill="#7c5740"/><rect x="90" y="70" width="1740" height="940" fill="#d7b98b" stroke="#563a2c" stroke-width="28"/><rect x="220" y="180" width="390" height="420" fill="#263f4b" stroke="#6d4931" stroke-width="22"/><path d="M415 180 V600 M220 390 H610" stroke="#6d4931" stroke-width="16"/><rect x="820" y="430" width="550" height="580" fill="#89613e"/><path d="M750 430 L1090 220 L1440 430Z" fill="#5b3b2c"/><rect x="910" y="520" width="170" height="490" fill="#493024"/>'
 :`<rect width="1920" height="1080" fill="${sky}"/><circle cx="1510" cy="170" r="82" fill="${night?'#e1e3ec':'#ffd88a'}" opacity=".95"/><path d="M0 520 Q270 390 520 510 T1040 485 T1560 500 T1920 450 V1080 H0Z" fill="${night?'#34463d':'#71945b'}"/><rect y="650" width="1920" height="430" fill="${ground}"/>${river?'<path d="M0 630 Q500 570 930 660 T1920 620 V920 Q1300 870 850 930 T0 900Z" fill="#668e9d"/><path d="M0 690 Q500 635 930 720 T1920 680" fill="none" stroke="#b8d5d8" stroke-width="9" opacity=".7"/>':''}<g fill="${night?'#282b2d':'#c7a779'}" stroke="${night?'#14191c':'#73523b'}" stroke-width="12"><path d="M170 650 L350 490 L530 650 V850 H170Z"/><path d="M125 650 L350 440 L575 650Z" fill="${night?'#24252b':'#8a553d'}"/><path d="M640 680 L790 555 L940 680 V840 H640Z"/><path d="M600 680 L790 510 L980 680Z" fill="${night?'#24252b':'#8a553d'}"/></g><g fill="#342c26"><rect x="275" y="720" width="80" height="130"/><rect x="735" y="720" width="75" height="120"/></g><g fill="${night?'#1c3027':'#426b42'}"><path d="M1190 710 Q1120 560 1200 430 Q1280 520 1245 700Z"/><path d="M1270 710 Q1260 500 1370 390 Q1420 540 1310 710Z"/><path d="M1150 540 Q1070 470 1100 390 Q1190 420 1190 530Z"/></g>`;
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="shade" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#fff" stop-opacity=".05"/><stop offset="1" stop-color="#17202a" stop-opacity=".22"/></linearGradient></defs>${scene}<rect width="1920" height="1080" fill="url(#shade)"/></svg>`;
 return svgAsset(svg)
}
function downloadJson(name:string,data:unknown){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function App(){
 const [workspace,setWorkspace]=useState('Animation'),[image,setImage]=useState<string|null>(null),[selectedBackground,setSelectedBackground]=useState<string|null>(null),[sceneSetup,setSceneSetup]=useState<{preset:string;camera:string;light:string;depth:string}>({preset:'Bengal Village',camera:'Medium Wide',light:'Warm Day',depth:'Flat'}),[zoom,setZoom]=useState(100),[playing,setPlaying]=useState(false),[frame,setFrame]=useState(1),[project,setProject]=useState<StudioProject>(createDefaultProject),[rig,setRig]=useState<CharacterRig|null>(null),[inspector,setInspector]=useState<'properties'|'face'|'camera'>('properties'),[tool,setTool]=useState('Select'),[status,setStatus]=useState('Ready'),[assets,setAssets]=useState<Asset[]>([]),[selectedLayer,setSelectedLayer]=useState('Character'),[camera,setCamera]=useState<Camera2D>(defaultCamera),[faceEdit,setFaceEdit]=useState<FaceAnimationValues>(defaultFaceAnimation),[selectedKeyframeId,setSelectedKeyframeId]=useState<string|null>(null);
 const inputRef=useRef<HTMLInputElement>(null),rigFileRef=useRef<HTMLInputElement>(null),mediaRef=useRef<HTMLInputElement>(null),bgRef=useRef<HTMLInputElement>(null);const scene=project.scenes.find(s=>s.id===project.activeSceneId)!;
 const characterTrack=scene.tracks.find(t=>t.kind==='character');const faceTrack=scene.tracks.find(t=>t.kind==='face');const rigTrack=scene.tracks.find(t=>t.kind==='rig');const motion=characterTrack?interpolateMotion(motionFromTrack(characterTrack.keyframes),frame):{x:0,y:0,rotation:0,scale:1};const face=faceTrack?faceValuesAtFrame(faceTrack.keyframes,frame):faceEdit;
 const rigKeys=useMemo(()=>rigTrack?rigTrack.keyframes.filter(k=>k.property==='pose').map(k=>({frame:k.frame,pose:poseFromTrackValue(k.value)})).sort((a,b)=>a.frame-b.frame):[],[rigTrack]);const rigPose=useMemo(()=>rig?(rigKeys.length?interpolatePose(rigKeys,frame):poseFromRig(rig)): {},[rig,rigKeys,frame]);
 const selectedKeyframe=useMemo(()=>{if(!selectedKeyframeId)return null;for(const t of scene.tracks){const k=t.keyframes.find(x=>x.id===selectedKeyframeId);if(k)return {track:t,keyframe:k}}return null},[scene,selectedKeyframeId]);
 useEffect(()=>{if(!selectedKeyframeId)return;const exists=scene.tracks.some(t=>t.keyframes.some(k=>k.id===selectedKeyframeId));if(!exists)setSelectedKeyframeId(null)},[scene,selectedKeyframeId]);
 useEffect(()=>{let cancelled=false;(async()=>{const restored=await loadLatestRecoverySnapshot();if(cancelled||!restored)return;setProject(restored);if(restored.sceneSetup)setSceneSetup(restored.sceneSetup);setAssets(restored.assets||[]);const background=restored.assets?.find(a=>a.type==='background');if(background?.source)setSelectedBackground(background.source);const character=restored.assets?.find(a=>a.type==='character');if(character?.source)setImage(character.source);setFrame(1);setStatus('Recovered latest project snapshot automatically')})();return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setFrame(f=>f>=scene.duration?1:f+1),1000/scene.fps);return()=>clearInterval(id)},[playing,scene.duration,scene.fps]);
 useEffect(()=>{let timer:number|undefined;const save=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{saveRecoverySnapshot({...project,assets}).catch(()=>{});},1000)};save();return()=>window.clearTimeout(timer)},[project,assets]);
 useEffect(()=>{const restore=(event:Event)=>{const detail=(event as CustomEvent<StudioProject>).detail;if(!detail)return;const restored=migrateProject(detail);setProject(restored);if(restored.sceneSetup)setSceneSetup(restored.sceneSetup);setAssets(restored.assets||[]);const background=restored.assets?.find(a=>a.type==='background');if(background?.source)setSelectedBackground(background.source);const character=restored.assets?.find(a=>a.type==='character');if(character?.source)setImage(character.source);setFrame(1);setWorkspace('Animation');setStatus('Project restored from recovery snapshot')};window.addEventListener('maya-shadow:restore-project',restore);return()=>window.removeEventListener('maya-shadow:restore-project',restore)},[]);
 useEffect(()=>installRenderFrameBridge(setFrame),[]);
 useEffect(()=>{const apply=(event:Event)=>{const detail=(event as CustomEvent<SceneSetup>).detail;if(!detail)return;setSceneSetup(detail);setProject(p=>({...p,sceneSetup:detail,updatedAt:new Date().toISOString()}));const framing:Record<string,number>={'Wide':0.88,'Medium Wide':0.96,'Medium':1.08,'Close Up':1.28};setCamera(c=>({...c,zoom:framing[detail.camera]??1}));setStatus('Scene applied • '+detail.preset+' • '+detail.camera+' • '+detail.light+' • '+detail.depth)};window.addEventListener('maya-shadow:scene-setup',apply);try{const saved=localStorage.getItem('maya-shadow-scene-director');if(saved){const parsed=JSON.parse(saved);if(parsed?.preset&&parsed?.camera&&parsed?.light&&parsed?.depth){setSceneSetup(parsed);const framing:Record<string,number>={'Wide':0.88,'Medium Wide':0.96,'Medium':1.08,'Close Up':1.28};setCamera(c=>({...c,zoom:framing[parsed.camera]??c.zoom}))}}}catch{}return()=>window.removeEventListener('maya-shadow:scene-setup',apply)},[]);
 const importCharacter=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const src=String(r.result);const replacement:Asset={id:makeId('asset'),name:f.name,type:'character',source:src,createdAt:new Date().toISOString()};const result=replaceCharacterAsset(assets,replacement,src);setImage(result.image);setAssets(result.assets);setWorkspace('Character');setStatus(rig?'Character replaced • rig and timeline preserved':'Character imported • ready for rig mapping')};r.readAsDataURL(f)};
 const importBackground=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const src=String(r.result);setAssets(a=>[...a,{id:makeId('asset'),name:f.name,type:'background',source:src,createdAt:new Date().toISOString()}]);setSelectedBackground(src);setWorkspace('Animation');setStatus('Background imported and applied to Animation Canvas')};r.readAsDataURL(f)};
 const importMedia=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const m=await readMediaFile(f);setAssets(a=>[...a,{id:m.id,name:m.name,type:m.type,source:m.source,createdAt:new Date().toISOString()}]);setWorkspace('Audio/Video');setStatus(`${m.type==='audio'?'Audio':'Video'} imported • ${m.duration.toFixed(1)}s`)};
 const updateScene=(next:typeof scene)=>setProject(p=>({...p,updatedAt:new Date().toISOString(),scenes:p.scenes.map(s=>s.id===scene.id?next:s)}));
 const addSceneSetupKeys=()=>{const track=scene.tracks.find(t=>t.kind==='scene');if(!track){setStatus('Camera / Scene track unavailable');return;}let next=scene;const values:[string,string][]=[['scene.preset',sceneSetup.preset],['scene.camera',sceneSetup.camera],['scene.light',sceneSetup.light],['scene.depth',sceneSetup.depth],['camera.x',String(camera.x)],['camera.y',String(camera.y)],['camera.rotation',String(camera.rotation)],['camera.zoom',String(camera.zoom)]];for(const [property,value] of values)next=addKeyframe(next,track.id,frame,property,value);updateScene(next);setSelectedLayer('Scene');setStatus('Scene setup keyframes saved at frame '+frame)};
 const addBackgroundKey=()=>{const track=scene.tracks.find(t=>t.kind==='background');if(!track){setStatus('Background track unavailable');return;}const asset=assets.find(a=>a.type==='background'&&a.source===selectedBackground);if(!asset){setStatus('Import or select a background before keyframing it');setWorkspace('Background');return;}const next=addKeyframe(scene,track.id,frame,'background.assetId',asset.id);updateScene(next);setSelectedLayer('Background');setStatus('Background keyframe saved at frame '+frame)};
 useEffect(()=>{const sceneTrack=scene.tracks.find(t=>t.kind==='scene');if(sceneTrack){const valueAt=(property:string)=>sceneTrack.keyframes.filter(k=>k.property===property&&k.frame<=frame).sort((a,b)=>b.frame-a.frame)[0]?.value;const preset=valueAt('scene.preset'),cameraValue=valueAt('scene.camera'),light=valueAt('scene.light'),depth=valueAt('scene.depth');if(typeof preset==='string'||typeof cameraValue==='string'||typeof light==='string'||typeof depth==='string'){setSceneSetup(current=>({preset:typeof preset==='string'?preset:current.preset,camera:typeof cameraValue==='string'?cameraValue:current.camera,light:typeof light==='string'?light:current.light,depth:typeof depth==='string'?depth:current.depth}));if(typeof cameraValue==='string'){const framing:Record<string,number>={'Wide':0.88,'Medium Wide':0.96,'Medium':1.08,'Close Up':1.28};setCamera(current=>({...current,zoom:framing[cameraValue]??current.zoom}))}}const cameraNumber=(property:string)=>{const keys=sceneTrack.keyframes.filter(k=>k.property===property&&Number.isFinite(Number(k.value))).sort((a,b)=>a.frame-b.frame);if(!keys.length)return null;const before=[...keys].reverse().find(k=>k.frame<=frame),after=keys.find(k=>k.frame>=frame);if(!before)return Number(after!.value);if(!after)return Number(before.value);if(before.frame===after.frame)return Number(before.value);const t=(frame-before.frame)/(after.frame-before.frame);return Number(before.value)+(Number(after.value)-Number(before.value))*t};const cx=cameraNumber('camera.x'),cy=cameraNumber('camera.y'),cr=cameraNumber('camera.rotation'),cz=cameraNumber('camera.zoom');if(cx!==null||cy!==null||cr!==null||cz!==null)setCamera(current=>({...current,x:cx??current.x,y:cy??current.y,rotation:cr??current.rotation,zoom:cz??current.zoom}));}const backgroundTrack=scene.tracks.find(t=>t.kind==='background');const bgKey=backgroundTrack?.keyframes.filter(k=>k.property==='background.assetId'&&k.frame<=frame).sort((a,b)=>b.frame-a.frame)[0];if(bgKey&&typeof bgKey.value==='string'){const bg=assets.find(a=>a.id===bgKey.value&&a.type==='background');if(bg?.source)setSelectedBackground(bg.source)}},[frame,scene,assets]);
 const addTimelineKey=()=>{if(!characterTrack)return;const next=addKeyframe(scene,characterTrack.id,frame,'transform',{x:motion.x,y:motion.y,rotation:motion.rotation,scale:motion.scale});const key=next.tracks.find(t=>t.id===characterTrack.id)?.keyframes.find(k=>k.frame===frame&&k.property==='transform');updateScene(next);if(key)setSelectedKeyframeId(key.id);setStatus(`Character keyframe created at frame ${frame}`)};
 const addFaceKey=(property:keyof FaceAnimationValues,value:number)=>{if(!faceTrack)return;const next=addKeyframe(scene,faceTrack.id,frame,property,value);const key=next.tracks.find(t=>t.id===faceTrack.id)?.keyframes.find(k=>k.frame===frame&&k.property===property);updateScene(next);if(key)setSelectedKeyframeId(key.id);setStatus(`Face keyframe • ${property} • frame ${frame}`)};
 const updateFace=(v:FaceAnimationValues)=>{setFaceEdit(v);if(!faceTrack||!faceTrack.keyframes.length)setStatus('Facial controls live • press ◆ to keyframe')};
 const updateRigPose=(pose:RigPose)=>{if(!rigTrack)return;const value=poseToTrackValue(pose);const next=addKeyframe(scene,rigTrack.id,frame,'pose',value);updateScene(next)};
 const addRigPoseKey=()=>{if(!rig||!rigTrack)return;const value=poseToTrackValue(rigPose);const next=addKeyframe(scene,rigTrack.id,frame,'pose',value);const key=next.tracks.find(t=>t.id===rigTrack.id)?.keyframes.find(k=>k.frame===frame&&k.property==='pose');updateScene(next);if(key)setSelectedKeyframeId(key.id);setStatus(`Rig pose keyframe created at frame ${frame}`)};
 const applyMotionFrames=(frames:Array<{frame:number;pose:RigPose}>,meta:{source:string;fps:number;target:string;scale:number;mirror:boolean;rootMotion:boolean})=>{if(!rig){setStatus('Import or create a character rig first, then apply the motion.');setWorkspace('Character');return;}if(!rigTrack){setStatus('Rig Controls track is unavailable in the active scene.');return;}let next=scene;for(const item of frames){if(item.frame>scene.duration)break;next=addKeyframe(next,rigTrack.id,Math.max(1,item.frame),'pose',poseToTrackValue(item.pose));}updateScene(next);setWorkspace('Character');setFrame(Math.max(1,Math.min(scene.duration,frames[0]?.frame||1)));setSelectedLayer('Rig Controls');setStatus(`Motion applied to rig timeline • ${frames.length} pose keyframes • ${meta.source}`)};
 const deleteSelectedKeyframe=()=>{if(!selectedKeyframe)return;updateScene(removeKeyframe(scene,selectedKeyframe.track.id,selectedKeyframe.keyframe.id));setSelectedKeyframeId(null);setStatus(`Keyframe deleted • frame ${selectedKeyframe.keyframe.frame}`)};
 const duplicateSelectedKeyframe=()=>{if(!selectedKeyframe)return;const next=duplicateKeyframe(scene,selectedKeyframe.track.id,selectedKeyframe.keyframe.id,frame);const key=next.tracks.find(t=>t.id===selectedKeyframe.track.id)?.keyframes.find(k=>k.frame===frame&&k.property===selectedKeyframe.keyframe.property);updateScene(next);if(key)setSelectedKeyframeId(key.id);setStatus(`Keyframe duplicated to frame ${frame}`)};
 const changeSelectedEasing=(easing:NonNullable<Keyframe['easing']>)=>{if(!selectedKeyframe)return;updateScene(setKeyframeEasing(scene,selectedKeyframe.track.id,selectedKeyframe.keyframe.id,easing));setStatus(`Easing changed to ${easing}`)};
 const createScene=()=>{const base=createDefaultProject().scenes[0];const next={...base,id:makeId('scene'),name:`Scene ${String(project.scenes.length+1).padStart(2,'0')}`};setProject(p=>({...p,activeSceneId:next.id,scenes:[...p.scenes,next],updatedAt:new Date().toISOString()}));setFrame(1);setStatus('New scene created');};
 const exportProject=()=>{saveRecoverySnapshot({...project,assets}).catch(()=>{});downloadJson(`${project.name.replace(/\s+/g,'-').toLowerCase()}.maya.json`,{...project,assets})};const exportRig=()=>rig&&downloadJson('character-rig.mayarig.json',rig);
 const importRig=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setRig(JSON.parse(String(r.result)));setStatus('Rig template imported')}catch{setStatus('Invalid rig JSON')}};r.readAsText(f)};const assetFor=(type:Asset['type'])=>assets.filter(a=>a.type===type);const renderTransform={transform:`translate(${motion.x}px,${motion.y}px) rotate(${motion.rotation}deg) scale(${motion.scale})`};
 const usePreset=(p:StudioPreset)=>{if(p.category==='character'){const source=p.sourceType==='image'&&p.source?p.source:makePresetCharacter(p.name);const replacement:Asset={id:makeId('asset'),name:p.name,type:'character',source,createdAt:new Date().toISOString()};const result=replaceCharacterAsset(assets,replacement,source);setImage(result.image);setAssets(result.assets);setWorkspace('Animation');setSelectedLayer('Character');setStatus(rig?`Character preset applied: ${p.name} • existing rig and timeline preserved`:`Character preset applied: ${p.name} • visible on canvas; open Character workspace to rig`)}else if(p.category==='background'){const source=p.sourceType==='image'&&p.source?p.source:makePresetBackground(p.name);const asset:Asset={id:makeId('asset'),name:p.name,type:'background',source,createdAt:new Date().toISOString()};setAssets(a=>[...a,asset]);setSelectedBackground(source);setWorkspace('Animation');setSelectedLayer('Background');setStatus(p.name+' background applied to Animation Canvas')}else{setStatus(`${p.name} preset selected • workflow preset only; no image asset is attached yet`)} };
 return <div className="studio"><header className="topbar"><div className="brand"><span className="brand-mark">M</span><div><strong>Maya Shadow</strong><small>Animation Studio</small></div></div><nav className="menus">{['File','Edit','View','Insert','Animate','Character','AI Tools','Export'].map(x=><span key={x}>{x}</span>)}</nav><div className="top-actions"><button onClick={exportProject}>Save Project</button><button onClick={()=>setWorkspace('Presets')}>Preset Library</button><button onClick={()=>setStatus('Undo stack ready')}>Undo</button><button className="primary" onClick={()=>setPlaying(v=>!v)}>{playing?'Stop':'Preview'}</button></div></header>
 <section className="toolbar"><div className="tool-group"><span className="group-label">Workspace</span>{workspaces.map(x=><button key={x} className={workspace===x?'active':''} onClick={()=>setWorkspace(x)}>{x}</button>)}</div><div className="tool-group"><span className="group-label">Zoom</span><button onClick={()=>setZoom(z=>Math.max(25,z-25))}>−</button><span className="zoom">{zoom}%</span><button onClick={()=>setZoom(z=>Math.min(300,z+25))}>+</button></div><div className="tool-group"><span className="group-label">Tool</span><strong className="tool-readout">{tool}</strong></div></section>
 <main className="workspace"><aside className="left-panel"><div className="panel-title">TOOLS</div><div className="tools-grid">{tools.map(([k,l])=><button key={k} title={l} className={tool===l?'selected-tool':''} onClick={()=>{setTool(l);setStatus(`${l} tool selected`)}}><b>{k}</b><span>{l}</span></button>)}</div><div className="panel-title section">CHARACTER PIPELINE</div><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={importCharacter}/><input ref={rigFileRef} type="file" accept="application/json,.mayarig.json" hidden onChange={importRig}/><button className="wide" onClick={()=>inputRef.current?.click()}>＋ Import Character</button><button className="wide" onClick={()=>setWorkspace('Character')}>✦ Auto Rig Map</button><button className="wide" onClick={()=>setWorkspace('Character')}>◎ Rig Editor</button><button className="wide" onClick={()=>rigFileRef.current?.click()}>⇩ Import Rig Template</button><button className="wide" onClick={exportRig} disabled={!rig}>⇧ Export Rig Template</button><div className="panel-title section">PRODUCTION</div><input ref={bgRef} type="file" accept="image/*" hidden onChange={importBackground}/><input ref={mediaRef} type="file" accept="audio/*,video/*" hidden onChange={importMedia}/><button className="wide" onClick={createScene}>＋ New Scene</button><button className="wide" onClick={()=>setWorkspace('Background')}>▣ Asset Library</button><button className="wide" onClick={()=>setWorkspace('Presets')}>✦ Preset Library</button><button className="wide" onClick={()=>bgRef.current?.click()}>▧ Import Background</button><button className="wide" onClick={()=>mediaRef.current?.click()}>♫ Import Audio / Video</button><button className="wide" onClick={()=>setWorkspace('Audio/Video')}>🎚 Professional Audio / Video</button><button className="wide" onClick={()=>setWorkspace('AI')}>🧠 AI Production Center</button><button className="wide" onClick={()=>setWorkspace('Drawing')}>✎ Drawing Studio</button></aside>
 <section className="canvas-area"><div className="canvas-tabs"><span className="tab active">{workspace==='Presets'?'Preset Library':scene.name}</span>{workspace!=='Presets'&&<span className="tab" onClick={createScene}>+ New Scene</span>}</div>{workspace==='Presets'?<PresetLibrary onUse={usePreset} onStatus={setStatus} onApplyMotion={applyMotionFrames}/>:workspace==='Character'?<div className="character-workspace">{rig?<><RigPreview rig={rig} frame={frame} pose={rigPose} poseFrames={rigKeys.map(k=>k.frame)} onPoseChange={updateRigPose} onPoseKeyframe={addRigPoseKey} onFrameChange={setFrame} onStatus={setStatus}/><MeshDeformationPreview rig={rig} pose={rigPose} image={image}/></>:<RigMapCanvas image={image} onRigCreated={setRig}/>}<FaceAnimationPreview values={face} image={image}/></div>:workspace==='Drawing'?<DrawingWorkspace onStatus={setStatus}/>:workspace==='Background'?<div className="asset-workspace"><div className="workspace-title">BACKGROUND & ENVIRONMENT</div><div className="asset-large-grid">{assetFor('background').map(a=><button key={a.id} className={selectedBackground===a.source?'active':''} onClick={()=>{setSelectedBackground(a.source);setWorkspace('Animation');setStatus('Background applied to Animation Canvas: '+a.name)}}><img src={a.source}/><span>{a.name}</span></button>)}<button className="asset-empty" onClick={()=>bgRef.current?.click()}>＋ Add Background</button></div></div>:workspace==='Audio/Video'?<AudioVideoStudioPanel assets={assets} onImport={()=>mediaRef.current?.click()} onStatus={setStatus}/>:workspace==='AI'?<AIProductionWorkspace onWorkspaceChange={setWorkspace} onPreview={()=>setPlaying(true)} onStatus={setStatus}/>:<div className="stage-wrap"><div className="stage" style={{transform:`scale(${zoom/100})`}}><div className="camera-frame" style={{transform:`translate(${-camera.x}px,${-camera.y}px) scale(${camera.zoom}) rotate(${-camera.rotation}deg)`}}><div className="scene-environment" data-scene-preset={sceneSetup.preset} data-scene-mood={sceneSetup.light} data-scene-depth={sceneSetup.depth}>{selectedBackground&&<img className="scene-background-image" src={selectedBackground} alt="Selected scene background"/>}<div className="scene-generated-layers"><div className="scene-far-layer"/><div className="scene-mid-layer"/><div className="scene-near-layer"/></div></div>{image?<img src={image} alt="Imported character" className="character-image" style={renderTransform}/>:<><div className="stage-cross">+</div><div className="stage-label">CANVAS<br/><small>{scene.width} × {scene.height}</small></div></>}</div></div></div>}</section>
 <aside className="right-panel"><div className="inspector-tabs"><button className={inspector==='properties'?'active':''} onClick={()=>setInspector('properties')}>Properties</button><button className={inspector==='face'?'active':''} onClick={()=>setInspector('face')}>Face Rig</button><button className={inspector==='camera'?'active':''} onClick={()=>setInspector('camera')}>Camera</button></div>{inspector==='face'?<><FaceAnimationPanel values={face} onChange={updateFace} onKeyframe={addFaceKey}/><FaceRigPanel values={face} onChange={updateFace} onKeyframe={addFaceKey}/><FaceAnimationPreview values={face} image={image}/></>:inspector==='camera'?<CameraPanel camera={camera} onChange={setCamera}/>:<><div className="panel-title">PROPERTIES</div><div className="property-card"><h3>{selectedLayer}</h3><p>{image?'Character asset loaded':'No object selected'}</p>{rig&&<div className="property-row"><span>Rig</span><strong>{rig.bones.length} bones</strong></div>}<div className="property-row"><span>Frame Transform</span><strong>{Math.round(motion.x)}, {Math.round(motion.y)}</strong></div><div className="property-row"><span>Face Track</span><strong>{faceTrack?.keyframes.length??0} keys</strong></div><div className="property-row"><span>Rig Pose Track</span><strong>{rigTrack?.keyframes.filter(k=>k.property==='pose').length??0} keys</strong></div>{rig&&<div className="property-row"><span>Mesh</span><strong>Grid deformation ready</strong></div>}</div><div className="panel-title section">LAYERS</div>{['Scene','Character','Eyes / Face','Mouth / Phonemes','Rig Controls','Background'].map((x,i)=><button className={`layer ${selectedLayer===x?'active':''}`} key={x} onClick={()=>setSelectedLayer(x)}><span>{i<2?'◉':'◇'}</span><b>{x}</b><i>{i<2?'Visible':''}</i></button>)}<div className="panel-title section">ASSETS ({assets.length})</div><div className="asset-grid"><div>Characters {assetFor('character').length}</div><div>Props</div><div>Backgrounds {assetFor('background').length}</div><div>Audio {assetFor('audio').length}</div></div></>}</aside></main>
 <section className="timeline"><div className="timeline-head"><div><b>TIMELINE</b><span> {scene.name}</span></div><div className="transport"><button onClick={()=>setFrame(Math.max(1,frame-1))}>◀</button><button className="play" onClick={()=>setPlaying(v=>!v)}>{playing?'■':'▶'}</button><button onClick={()=>setFrame(Math.min(scene.duration,frame+1))}>▶</button><span>F {frame} / {scene.duration}</span></div><div className="timeline-edit-tools"><button onClick={addTimelineKey}>＋ Character Key</button><button onClick={addSceneSetupKeys}>◆ Scene Key</button><button onClick={addBackgroundKey}>▧ BG Key</button><button onClick={deleteSelectedKeyframe} disabled={!selectedKeyframe}>Delete</button><button onClick={duplicateSelectedKeyframe} disabled={!selectedKeyframe}>Duplicate to Current</button><select value={selectedKeyframe?.keyframe.easing||'linear'} disabled={!selectedKeyframe} onChange={e=>changeSelectedEasing(e.target.value as NonNullable<Keyframe['easing']>)} aria-label="Keyframe easing"><option value="linear">Linear</option><option value="ease-in">Ease In</option><option value="ease-out">Ease Out</option><option value="ease-in-out">Ease In Out</option></select><button onClick={()=>setFrame(1)}>⏮</button></div></div><div className="timeline-body"><div className="track-labels">{scene.tracks.map(t=><div key={t.id}>{t.name}</div>)}</div><div className="tracks"><div className="ruler">{Array.from({length:12},(_,i)=><span key={i}>{i+1}</span>)}</div>{scene.tracks.map(t=><div className="track" key={t.id}>{t.keyframes.map(k=><button className={`keyframe ${selectedKeyframeId===k.id?'selected':''}`} key={k.id} style={{left:`${Math.max(8,k.frame*3)}px`}} title={`${k.property} • frame ${k.frame} • ${k.easing||'linear'}`} onClick={()=>{setSelectedKeyframeId(k.id);setFrame(k.frame);setStatus(`Selected ${k.property} keyframe • frame ${k.frame}`)}}/>)}</div>)}</div></div></section>
 <footer><span>{status}</span><span>Scene {scene.width}×${scene.height} • {scene.fps} FPS • {Math.round((frame/scene.fps)*10)/10}s</span></footer></div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
