import React,{useEffect,useRef,useState} from 'react';
import './drawing.css';

type Props={brushSize?:number;onStatus?:(message:string)=>void;activeTool?:string;initialImage?:string|null;onChange?:(dataUrl:string)=>void;onSendToCanvas?:(dataUrl:string)=>void};
type Point={x:number;y:number};
type Snapshot=ImageData;
const supportedTools=['Brush','Pen','Eraser','Line','Rectangle','Ellipse','Text'];
export default function DrawingCanvas({brushSize=4,onStatus,activeTool='Brush',initialImage,onChange,onSendToCanvas}:Props){
 const ref=useRef<HTMLCanvasElement>(null),startRef=useRef<Point|null>(null),baseRef=useRef<Snapshot|null>(null),history=useRef<Snapshot[]>([]);
 const [drawing,setDrawing]=useState(false),[size,setSize]=useState(brushSize),[colour,setColour]=useState('#252a35'),[textValue,setTextValue]=useState('Text');
 const tool=supportedTools.includes(activeTool)?activeTool:'Brush';
 useEffect(()=>{const c=ref.current;if(!c||!initialImage)return;const ctx=c.getContext('2d');if(!ctx)return;const im=new Image();im.onload=()=>{ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height)};im.src=initialImage},[initialImage]);
 const notifyChange=()=>{const c=ref.current;if(c&&onChange)try{onChange(c.toDataURL('image/png'))}catch{}};

 const point=(e:React.PointerEvent<HTMLCanvasElement>):Point|undefined=>{const c=ref.current;if(!c)return;const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};};
 const remember=()=>{const c=ref.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;try{history.current.push(ctx.getImageData(0,0,c.width,c.height));if(history.current.length>8)history.current.shift()}catch{}};
 const drawShape=(ctx:CanvasRenderingContext2D,a:Point,b:Point)=>{ctx.strokeStyle=colour;ctx.fillStyle=colour;ctx.lineWidth=size;ctx.lineCap='round';ctx.lineJoin='round';if(tool==='Line'){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}else if(tool==='Rectangle'){ctx.strokeRect(a.x,a.y,b.x-a.x,b.y-a.y)}else if(tool==='Ellipse'){ctx.beginPath();ctx.ellipse((a.x+b.x)/2,(a.y+b.y)/2,Math.max(1,Math.abs(b.x-a.x)/2),Math.max(1,Math.abs(b.y-a.y)/2),0,0,Math.PI*2);ctx.stroke()}};
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{const c=ref.current,p=point(e);if(!c||!p)return;const ctx=c.getContext('2d');if(!ctx)return;if(tool==='Text'){remember();ctx.save();ctx.fillStyle=colour;ctx.font=`600 ${Math.max(18,size*4)}px Inter, sans-serif`;ctx.fillText(textValue||'Text',p.x,p.y);ctx.restore();onStatus?.('Text object drawn on the illustration canvas');return}remember();startRef.current=p;baseRef.current=ctx.getImageData(0,0,c.width,c.height);c.setPointerCapture(e.pointerId);setDrawing(true);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=tool==='Eraser'?size*2:size;ctx.strokeStyle=colour;ctx.globalCompositeOperation=tool==='Eraser'?'destination-out':'source-over';ctx.beginPath();ctx.moveTo(p.x,p.y);if(tool==='Brush'||tool==='Pen'||tool==='Eraser')ctx.lineTo(p.x+.01,p.y+.01);ctx.stroke();};
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing)return;const c=ref.current,p=point(e),start=startRef.current,ctx=c?.getContext('2d');if(!c||!p||!start||!ctx)return;if(['Line','Rectangle','Ellipse'].includes(tool)){if(baseRef.current)ctx.putImageData(baseRef.current,0,0);drawShape(ctx,start,p);return;}ctx.globalCompositeOperation=tool==='Eraser'?'destination-out':'source-over';ctx.strokeStyle=colour;ctx.lineWidth=tool==='Eraser'?size*2:size;ctx.lineCap='round';ctx.lineJoin='round';ctx.lineTo(p.x,p.y);ctx.stroke();};
 const finish=()=>{if(!drawing)return;setDrawing(false);startRef.current=null;baseRef.current=null;const ctx=ref.current?.getContext('2d');if(ctx)ctx.globalCompositeOperation='source-over';onStatus?.(`${tool} drawing committed`);notifyChange();};
 const undo=()=>{const c=ref.current,last=history.current.pop();if(!c||!last){onStatus?.('Nothing to undo on the drawing layer');return}c.getContext('2d')?.putImageData(last,0,0);notifyChange();onStatus?.('Last drawing action undone')};
 const clear=()=>{const c=ref.current;if(!c)return;remember();c.getContext('2d')?.clearRect(0,0,c.width,c.height);notifyChange();onStatus?.('Drawing layer cleared')};
 const exportPng=()=>{const c=ref.current;if(!c)return;c.toBlob(blob=>{if(!blob){onStatus?.('PNG export failed');return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='maya-shadow-drawing.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);onStatus?.('Drawing exported as transparent PNG')},'image/png')};
 const sendToCanvas=()=>{const c=ref.current;if(!c)return;if(!onSendToCanvas){onStatus?.('Canvas insertion is unavailable in this workspace');return}onSendToCanvas(c.toDataURL('image/png'));onStatus?.('Drawing sent to Animation Canvas')};
 return <div className="drawing-tool"><div className="drawing-controls"><b>ILLUSTRATION</b><span className="drawing-active-tool">{tool}</span><label>Size <input type="range" min="1" max="40" value={size} onChange={e=>setSize(+e.target.value)}/><span>{size}px</span></label><label>Colour <input aria-label="Drawing colour" type="color" value={colour} onChange={e=>setColour(e.target.value)}/></label>{tool==='Text'&&<label>Text <input className="drawing-text-input" value={textValue} onChange={e=>setTextValue(e.target.value)} aria-label="Text content"/></label>}<button onClick={undo}>Undo</button><button onClick={clear}>Clear</button><button onClick={exportPng}>Export PNG</button><button className="drawing-export" onClick={sendToCanvas}>Send to Canvas →</button></div><div className="drawing-hint">{tool==='Text'?'Set the text above, then click the canvas to place it.':(['Line','Rectangle','Ellipse'].includes(tool)?'Drag on the canvas to draw the selected shape.':'Drag to draw; use Undo to reverse the last stroke.')}</div><canvas ref={ref} width={1920} height={1080} className={`drawing-canvas drawing-tool-${tool.toLowerCase()}`} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}/></div>;
}
